### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by tdsmith** [danielbuechele/goofy#100]
I'm seeing a crash on launch; here's the stack trace: https://gist.github.com/anonymous/b1669ad6389d3e987317

After clearing all browsing data in Safari and running `find ~/Library -name *oofy* -delete` I can launch goofy and get to the login screen, but then goofy crashes after I successfully authenticate.

**Comment by danielbuechele** [comment]
Looks like you are on a old version. Can you try downloading the latest version?

**Comment by tdsmith** [comment]
Yep, sorry! Works now. I filed https://github.com/caskroom/homebrew-cask/pull/11818 to fix homebrew-cask's download URL.
