### ISSUE TITLE
Not possible to send files

### ISSUE THREAD

**Issue by DotTheI** [danielbuechele/goofy#106]
Goofy doesn't send files neither via the button on the main window nor by dragging & dropping.

**Comment by danielbuechele** [comment]
Yeah I am wondering what the problem here is, but I can reproduce it, too. I hope I'll find the issue. Any help is highly appreciated /cc @peterjosling

**Comment by fibigerg** [comment]
Hi, I cannot send any files through Goofy. It is a really important feature, because I have to open f****** facebook website every time i want to send files :/

**Comment by fibigerg** [comment]
I have just found out that it is www.messenger.com problem. I get the same error trying send files there.

**Comment by andremiguelaa** [comment]
I think not... I can send files through messenger.com and not with Goofy

**Comment by andremiguelaa** [comment]
Merge with #90 ?

**Comment by Karlheinzniebuhr** [comment]
having the same issue

**Comment by jklp** [comment]
@andremiguelaa Yep same issue as #90, have created a pull request to fix it too so hopefully fixed soon :)

**Comment by andre-ascensao-bold** [comment]
@jklp Great news ;)

**Comment by andremiguelaa** [comment]
@jklp Great news!
