### ISSUE TITLE
Application freezes when launching on startup

### ISSUE THREAD

**Issue by cprecioso** [danielbuechele/goofy#11]
When setting the app to launch on startup, it starts loading, showing sometimes the "It takes unusually long to load...", but freezes before actually loading the WebView. When I try to hit ⌘R, it crashes.

**Comment by xypaul** [comment]
Yeah app doesn't seem to work for me at the moment. Must have been about 2-3 days since it worked last.

**Comment by danielbuechele** [comment]
@xypaul Does this only happen if you automatically start the app on launch or also when you launch it manually? Tried redownloading it from goofyapp.com?
