### ISSUE TITLE
Icons in messaging input area are not retine/hi-DPI ready

### ISSUE THREAD

**Issue by csi7585** [danielbuechele/goofy#110]
![screen shot 2015-06-28 at 3 48 11 pm](https://cloud.githubusercontent.com/assets/1253402/8398669/ff3e921a-1dac-11e5-815f-ff2d75968cda.png)

**Comment by danielbuechele** [comment]
Sometimes they are. This is a bug from Facebook delivering the wrong icons.

On 29.06.2015, at 00:47, Chris Sinco <notifications@github.com> wrote:

[image: screen shot 2015-06-28 at 3 48 11 pm]
<https://cloud.githubusercontent.com/assets/1253402/8398669/ff3e921a-1dac-11e5-815f-ff2d75968cda.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/danielbuechele/goofy/issues/110>.
