### ISSUE TITLE
Message context menu doesn't show up

### ISSUE THREAD

**Issue by mrjefftang** [danielbuechele/goofy#112]
Clicking on the circle with '...' next to a message doesn't show the contextual menu for 'Mute', 'Delete', 'Mark as Unread', 'Mark as Spam'.

**Comment by jklp** [comment]
Sorry a little new this but pull request with fix can be found at https://github.com/danielbuechele/goofy/pull/126

Thanks!

**Comment by jklp** [comment]
Ok finally fixed it, see pull request https://github.com/danielbuechele/goofy/pull/127 for fix :)

**Comment by danielbuechele** [comment]
fixed
