### ISSUE TITLE
El Capitan Update

### ISSUE THREAD

**Issue by MrWalkman** [danielbuechele/goofy#114]
I know it's still time til El Capitan will be officially released, but Goofy isn't showing the chat list on the left on El Capitan. Composing is also not working.

Thanks!

**Comment by BushidoWolf** [comment]
I'm having the same issue. Chat history does not show and will not refresh. Though on mine, the last used chat window is open with history intact, but composing a message (new or in the open chat window) are not working.

**Comment by leifniem** [comment]
+1 can confirm this

**Comment by BushidoWolf** [comment]
Latest Patch from Apple fixed the issue for me. El Captain had an issue with 32-bit applications that the latest update resolved. If the others can verify, we can close this problem.

**Comment by MrWalkman** [comment]
I installed the latest patch as well, but no change for me

**Comment by leifniem** [comment]
Patch installed. Seems fine until now in my case.

**Comment by ovlach** [comment]
Patch installed, no change for me.
