### ISSUE TITLE
Replying from notification doesn't submit

### ISSUE THREAD

**Issue by kalprestito** [danielbuechele/goofy#12]
When replying from a notification, the text is entered into the text box, but not actually submitted.

**Comment by bliker** [comment]
yep, confirmed :)

**Comment by danielbuechele** [comment]
This looks like a timing issue. I now wait 50ms between each action: https://github.com/danielbuechele/goofy/blob/master/server/src/fb.js#L124-L132
Is this still appearing in the current version from github or is it only in the release version?

**Comment by kalprestito** [comment]
Confirmed, not happening as of 555467b45e137cf2d8b639575acc89c0881ceb63
