### ISSUE TITLE
New message dialog doesn't show up when icon clicked

### ISSUE THREAD

**Issue by bzx** [danielbuechele/goofy#120]
Using 2.1.3

The new message icon in the left pane does not show the dialog to type the message. Also the cursor on hover over that icon does not change to pointer (but the icon itself is clickable - active state is there).

**Comment by lehni** [comment]
I am experiencing the same issue on Version 2.1.3 (647)

**Comment by jklp** [comment]
Created pull request at https://github.com/danielbuechele/goofy/pull/128 which fixes this

**Comment by danielbuechele** [comment]
fixed
