### ISSUE TITLE
Weird layout in small window

### ISSUE THREAD

**Issue by Sheraff** [danielbuechele/goofy#122]
Using goofy 2.1.3 on latest Yosemite.

![screen shot 2015-07-23 at 11 30 54](https://cloud.githubusercontent.com/assets/1325721/8847387/7c0960d8-312e-11e5-9656-f3c6c6d6b874.png)

**Comment by DotTheI** [comment]
I had the same issue with 2.1.3 https://github.com/danielbuechele/goofy/issues/119 Downgraded to 2.1.2 and that resolved the problem

**Comment by danielbuechele** [comment]
fixed in 2.2.0
