### ISSUE TITLE
Smaller font

### ISSUE THREAD

**Issue by kubofonista** [danielbuechele/goofy#124]
Current font is too big,
Please add option to make it smaller

**Comment by lucasromanomr** [comment]
Also I miss being able to resize the font size.

**Comment by DotTheI** [comment]
Same here

**Comment by seanyhc** [comment]
The current version (2.2.5) is too small for me.
Wish there is a command +/- keyboard shortcut for changing the font size

**Comment by ingemar** [comment]
Bump
