### ISSUE TITLE
Notifications on muted conversations

### ISSUE THREAD

**Issue by GandalfSaxe** [danielbuechele/goofy#125]
There shouldn't be notifications from muted conversations. I hope it's possible, perhaps even easy to fix?

**Comment by GandalfSaxe** [comment]
Ah sorry it's a duplicate of these:

https://github.com/danielbuechele/goofy/pull/117
https://github.com/danielbuechele/goofy/issues/54

**Comment by danielbuechele** [comment]
fixed

**Comment by GandalfSaxe** [comment]
You rock Daniel! Thanks, Goofy just became 1000x better :+1:

**Comment by joallard** [comment]
Selector has now changed to `56ck` >:(
