### ISSUE TITLE
Internationalization?

### ISSUE THREAD

**Issue by cprecioso** [danielbuechele/goofy#13]
I'd like to translate the app into Spanish, but I have minimal knowledge of Mac app developing. I added a new localization from the project info page in Xcode, but when trying to edit the new file (`es.lproj/MainMenu.strings`), it prompts me to translate all not only the Goofy-specific strings, but also all the standard Mac strings like `File`, `Edit`, `Window` menus, and its items. Is there a way to default this strings into the standard translation included with OS X? I assume there's one since all localized apps use the same exact strings and I haven't found even a single typo.

**Comment by danielbuechele** [comment]
@cprecioso you can help translating it here: https://docs.google.com/spreadsheets/d/1ygCDE0GAG94pio2SLmTzn5rqSEWx84TAgCeBZEUXZFs/edit?usp=sharing

**Comment by Risengan** [comment]
I've finished (and also corrected) all French translations! :-)

**Comment by cprecioso** [comment]
@danielbuechele Spanish done too!
