### ISSUE TITLE
"Get the app" banner visible after update (2.2.0)

### ISSUE THREAD

**Issue by asherism** [danielbuechele/goofy#133]
Tried reloading the page and cycling the app. No fix.

**Comment by danielbuechele** [comment]
Can anyone provide me the classname of this banner?

**Comment by asherism** [comment]
<img width="387" alt="screen shot 2015-08-07 at 11 00 53 am" src="https://cloud.githubusercontent.com/assets/11524787/9137402/a807c51e-3cf3-11e5-9842-256e5e2e5abd.png">
