### ISSUE TITLE
In the new 2.2.0, some emoticons no longer appear

### ISSUE THREAD

**Issue by fredefl** [danielbuechele/goofy#134]
Like these, for example:

<img width="465" alt="skaermbillede 2015-08-07 kl 20 07 02" src="https://cloud.githubusercontent.com/assets/599073/9142459/1453d8a6-3d40-11e5-802f-7a344849700a.png">

Note that Facebook converts them in the 'write a message'-box, however, it doesn't render them in the chat conversation view. 
- somehow OSX takes over there, instead.

**Comment by ivancuric** [comment]
Noticed the same thing.

**Comment by danielbuechele** [comment]
There are the emojis where I couldn't find a good native one. Any suggestions?
```
    "emoticon_pacman": ":v",
    "emoticon_grumpy": ">:(",
    "emoticon_unsure": ":/",
    "emoticon_glasses": "8)",
    "emoticon_upset": ">:o",
    "emoticon_colonthree": ":3",
    "emoticon_kiss": ":*",
    "emoticon_shark": "(^^^)",
    "emoticon_robot": ":|]",
    "emoticon_putnam": ":putnam:",
```

**Comment by jklp** [comment]
Not sure why you want to replace the standard FB emojis (to be honest I like the standard FB ones :) )?  But if the goal to match the iOS app not all of them are replaced (see screen shot of all emojis typed in below)

![photo 11-08-2015 10 05 18 am](https://cloud.githubusercontent.com/assets/1784679/9187150/946e1fb0-4010-11e5-827e-c939e1ef8a0d.png)

**Comment by danielbuechele** [comment]
I need to replace them to be able to show them in the notification pop up.
Also I think it gives the app a little more native look. Thanks for
pointing out the thing with iOS messenger, I thing it's a good way to go on
par with it.

On 11.08.2015, at 02:08, Jerrold Poh <notifications@github.com> wrote:

Not sure why you want to replace the standard FB emojis (to be honest I
like the standard FB ones :) )? But if the goal to match the iOS app not
all of them are replaced (see screen shot of all emojis typed in below)

[image: photo 11-08-2015 10 05 18 am]
<https://cloud.githubusercontent.com/assets/1784679/9187150/946e1fb0-4010-11e5-827e-c939e1ef8a0d.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/danielbuechele/goofy/issues/134#issuecomment-129651595>.

**Comment by ivancuric** [comment]
I believe that the right way to go is like in [messenger for desktop](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues), since you get conflicting aesthetics this way. Meaning - don't replace them.

**Comment by bendywalker** [comment]
I agree with @danielbuechele in that Apple's Emoji look better and provide a more consistent experience across Messenger on iOS and Goofy on OS X. However, if a lot of people prefer Facebook's native Emoji, maybe a preference could be added?

**Comment by ivancuric** [comment]
There is also another bug. In the notifications panel, every emoticon is preceded by the string "emoticon".

**Comment by deusy** [comment]
+1 for having a preference for keeping the Facebook emoji. I much prefer them.

**Comment by danielbuechele** [comment]
So, all emojis should be visible now, some as text others as native Apple emojis, similar to Messenger on iOS. The discussion about native vs. Facebook's emojis is another issue.
