### ISSUE TITLE
Crying face emoji gets apostrophe replaced 

### ISSUE THREAD

**Issue by cprecioso** [danielbuechele/goofy#135]
Whenever writing the :cry: emoji from text `:'(`, the apostrophe `'` changes into the typographic apostrophe `’`, so Facebook doesn't recognize it nor change it automatically into the emoji.

**Comment by RvMouche** [comment]
Seems like a default OS X problem. Maybe adding code to change :‘( back to
:'( would help in all cases.

**Comment by danielbuechele** [comment]
I don't think fighting agains OS X is a good idea. Perhaps this setting in the System Preferences can help.
![screen shot 2015-08-17 at 15 35 40](https://cloud.githubusercontent.com/assets/685740/9305978/ba70fa18-44f5-11e5-8bc1-61c7ef80a351.png)
