### ISSUE TITLE
Add "Report an Issue" item in menu

### ISSUE THREAD

**Issue by joallard** [danielbuechele/goofy#136]
I've had to [bother](https://twitter.com/jonathanallard/status/633087631375466496) our venerable developer @danielbuechele on Twitter to find this repo, so I'd suggest a "Report an Issue" item in the **Goofy** menu that leads here or possibly to a Wiki page describing how to do that and how not to ;o) I'm up for writing a draft for that Wikipage if needed.

**Comment by RvMouche** [comment]
That would be a great idea :)

**Comment by tenpaiyomi** [comment]
Created a pull request, https://github.com/danielbuechele/goofy/pull/158
