### ISSUE TITLE
Superfluous emoji text in notification

### ISSUE THREAD

**Issue by joallard** [danielbuechele/goofy#137]
Following message:
<img width="133" alt="" src="https://cloud.githubusercontent.com/assets/949482/9311360/b8b465d2-44e3-11e5-8fc8-15dd3f43f5af.png">

Creates notification:
<img width="335" alt="" src="https://cloud.githubusercontent.com/assets/949482/9311359/b884be90-44e3-11e5-9505-611994f59d1b.png">

v2.2.1 (817)

**Comment by filenox** [comment]
I'm having the same issue. (Goofy 2.2.1 on El Capitan)
