### ISSUE TITLE
Paste files/pictures?

### ISSUE THREAD

**Issue by GandalfSaxe** [danielbuechele/goofy#141]
Is it technically possible to allow files / pictures to be pasted into conversations simply by copy-paste?

**Comment by danielbuechele** [comment]
Yes it is possible to do so. However sometimes this function breaks due to Facebook's changes. Currently it should be possible to e.g. take a screenshot into you pasteboard and paste it into Goofy using CMD+V

**Comment by GandalfSaxe** [comment]
Pasting a screenshot from the pasteboard with Cmd+V in goofy doesn't work for me unfortunately. Hope this can be fixed sometime.

On a related note, how about adding a button for general file attachments next to the photo attachments?
