### ISSUE TITLE
Characters jumbled after pressing space.

### ISSUE THREAD

**Issue by Nailer** [danielbuechele/goofy#143]
Typing the following sentence:
This is a test sentence

Results in this:
this s  est entencestai

After every space, the caret starts inserting characters after the caret, instead of before. Started happening about a week ago.

OSX 10.10.5, Safari 8.8

**Comment by danielbuechele** [comment]
This is super weird! Can not reproduce it.

**Comment by tomky** [comment]
Second that. Usually happened after using a period of time. Especially when typing using Chinese Input Method.

OSX 10.10.5 Safari 8.0.8

**Comment by Nailer** [comment]
Worked today. Not sure why. Maybe due to restarting my mac.
