### ISSUE TITLE
Field for text input is gone

### ISSUE THREAD

**Issue by kitze** [danielbuechele/goofy#148]
When i opened Goofy today the input for replying was gone. Must be some change on Facebook's end.

**Comment by najela** [comment]
At my end, the input appears to be above  my messages instead of below

<img width="1667" alt="screen shot 2015-09-23 at 06 02 07" src="https://cloud.githubusercontent.com/assets/4196457/10038150/b82b3310-61b8-11e5-9d84-3a087b5abf0a.png">

**Comment by Murkrage** [comment]
It's above my messages as well. Not exactly user friendly, could it be a bad commit?

**Comment by danielbuechele** [comment]
I didn't change anything on Goofy. Must be a change on Facebook's side. But I haven't yet figured out what's going on here. Help is appreciated!

**Comment by Murkrage** [comment]
Really wish I could help, but no experience in swift at all

**Comment by danielbuechele** [comment]
Could you guys reload Goofy (CMD+R) or restart it and let me know if the error is fixed?

**Comment by Murkrage** [comment]
Fixed :)

**Comment by najela** [comment]
Fixed for me too :+1:
