### ISSUE TITLE
Textbox does not function properly after some time

### ISSUE THREAD

**Issue by wrsulliv** [danielbuechele/goofy#149]
I have noticed that the longer the app is open, the longer it takes for text to appear in the textbox.  I am currently running Goofy under OSX 10.10.4.  Eventually I am required to restart the program to fix the issue, but it usually slowly degrades back to its former state.

**Comment by danielbuechele** [comment]
I heard of bugs like this before, but have no idea where it might come from. I am wondering if bugs like this also occur in messenger.com accessed through the browser and just nobody has a browser window opened that long...

**Comment by Serneum** [comment]
I also experience the eventual slowdown. Sometimes while I'm typing, the textbox will also just stop accepting input until I reload the app

**Comment by wrsulliv** [comment]
Hmm, I think I'll do some experimenting and see if I notice the slow down using messenger.com
