### ISSUE TITLE
All links redirect to Facebook

### ISSUE THREAD

**Issue by Serneum** [danielbuechele/goofy#150]
For the last two or three days, every link I receive gets redirected through Facebook, which then automatically tries to log me in (probably from LastPass) and fails.

Links look like this before the login attempt.
`https://l.messenger.com/l.php?u=http%3A%2F%2Fwordpress.stackexchange.com%2Fquestions%2F100220%2Fcustom-post-type-current-menu-item-not-applying-on-custom-post-type-archive-pag&h=sAQEREagu`

Links used to open up fine. Do you have any ideas why I can be logged in on Facebook but the links from Messenger/Goofy take me to a Facebook page that thinks I need to authenticate?

**Comment by tenpaiyomi** [comment]
Just created a pull request for this, https://github.com/danielbuechele/goofy/pull/156

**Comment by danielbuechele** [comment]
fixed in v2.2.3
