### ISSUE TITLE
Pixelated vectors

### ISSUE THREAD

**Issue by xrisk** [danielbuechele/goofy#151]
The read and sent symbols are pixelated. I don’t know whether this is Facebook’s fault or not, but filing as an issue.
<img width="126" alt="screen shot 2015-09-25 at 5 19 15 pm" src="https://cloud.githubusercontent.com/assets/10669859/10099720/f2172d34-63a9-11e5-8c7a-305f94d1186d.png">

**Comment by tenpaiyomi** [comment]
This is an issue on Facebook's side, as the assets from the same source as messenger.com.  If you go to messenger.com in your browser and increase the font size, you'll notice the same pixelization.
