### ISSUE TITLE
Messages not sent

### ISSUE THREAD

**Issue by joallard** [danielbuechele/goofy#152]
I've been struggling with this for a few weeks now. You submit a message (or read receipt), and it doesn't go through to the FB server. (empty circle) Sometimes it does, but it's very unreliable. I've tested the same on Messenger.com and the messages go through fine. I understand it's tricky to diagnose since it happens about half of the time, but I'm wondering whether someone else had the same issues.

**Comment by tenpaiyomi** [comment]
@joallard I've experienced similar but, thus far, have been unable to figure out exactly what causes the problem.  If I close Goofy and reopen it, the same messages will generally send fine.

**Comment by joallard** [comment]
Don't remember getting this in a while, will close for now.
