### ISSUE TITLE
Message app integration possibility

### ISSUE THREAD

**Issue by kiler129** [danielbuechele/goofy#153]
I don't know whatever it's possible, but it may be a nice feature to integrate Goofy with Messages app.
Currently I use XMPP to integrate Google Hangouts and Facebook, but it's really not an good solution (no images, no messages when I was offline etc.).

**Comment by tenpaiyomi** [comment]
Not really possible, Facebook has deprecated their Chat API/XMPP protocol in favor of Messenger.com.  Assuming that, as some point in the future, they open up Messenger.com with some sort of an API, it might be able to be looked into then, but as is right now, Goofy is just a wrapper for Messenger.com.

**Comment by danielbuechele** [comment]
What @tenpaiyomi said.
