### ISSUE TITLE
New message to new contact doesn't work

### ISSUE THREAD

**Issue by eliduke** [danielbuechele/goofy#155]
I clicked new message, typed in a friend's name, found her, typed the message, hit enter and nothing happens. I can try to get more specific if you need to, but is anyone else having this problem?

**Comment by tenpaiyomi** [comment]
@eliduke Did this happen with a new friend or just a brand new conversation?  I tried to recreate it but was unable to.

**Comment by eliduke** [comment]
I just tried it again and it worked flawlessly. Did you sprinkle some pixie dust on my computer?!

**Comment by tenpaiyomi** [comment]
Absolutely :) Glad it worked.  If it happens again, feel free to open another ticket with general details and I'll try to recreate it on my end to see if I can fix it.
