### ISSUE TITLE
Twitching edit text box/footer 

### ISSUE THREAD

**Issue by elainedizon** [danielbuechele/goofy#160]
When chatting with someone frequently, edit text box is twiching which is really annoying.

**Comment by kevinjalbert** [comment]
I see the same issue. It is also a recent issue that I have noticed (within this week).

**Comment by danielbuechele** [comment]
I heard from a small group of users having this issue. However, I don't have any idea what this might be. Some reported that resizing the window fixed the problem for them.

**Comment by kevinjalbert** [comment]
Interesting that does seem to fix it (resizing it for more width).

I normally have it half my screen's width so I never thought of resizing it.

**Comment by joallard** [comment]
I've been resizing larger and larger since I've first had this problem :/
