### ISSUE TITLE
Copy-paste from Word generates image

### ISSUE THREAD

**Issue by lukasschwab** [danielbuechele/goofy#161]
When I copy-paste text from Microsoft Word into Goofy, goofy generates an image that maintains that text's styling. The text is then sent as an image.

This is bizarre, persistent when I reload the app, and does not happen when I copy-paste text into the Facebook web interface or messenger.com.

<img width="1305" alt="screen shot 2015-10-11 at 8 21 51 pm" src="https://cloud.githubusercontent.com/assets/4955943/10421075/c1bb80b4-7055-11e5-97c1-a871ee989655.png">

**Comment by danielbuechele** [comment]
This seems to be some weird behaviour from the new Office apps. The same is happening in Slack for example. I am not sure if I can do anything about this.

**Comment by TCB13** [comment]
Yeah, this is seriously annoying.
