### ISSUE TITLE
Goofy hangs on loading when the system boots up

### ISSUE THREAD

**Issue by neoyoli** [danielbuechele/goofy#162]
When Goofy is set as login item, it hangs on, and even Command + R doesn't help, needs to be restarted to bring the chat UI in.

![screen shot 2015-10-12 at 10 23 45](https://cloud.githubusercontent.com/assets/2356354/10424012/c2d61c90-70cb-11e5-91d7-25bd064784ab.png)

**Comment by permagnus** [comment]
Same here.

**Comment by carstn** [comment]
Same here, although mine looks slightly different. 
![screen shot 2015-11-21 at 9 03 03 pm](https://cloud.githubusercontent.com/assets/6798030/11322041/e924d4ca-9094-11e5-89fd-79de8ae83209.png)

It hangs indefinitely, and the spinner doesn't move. Clicking on any elements crashes it. Once relaunched, it works fine.

Goofy version 2.2.3 (927)
OS X El Capitan version 10.11.1

**Comment by neoyoli** [comment]
with the new version (2.2.4), the bug is still present.

**Comment by metakirby5** [comment]
@danielbuechele this should be closed 😄

**Comment by neoyoli** [comment]
as for 2.2.6, the issue is still there.
