### ISSUE TITLE
Enable Web Inspector

### ISSUE THREAD

**Issue by cprecioso** [danielbuechele/goofy#17]
It would be great if the web inspector could be enable, in order to modify and examine better.

**Comment by kalprestito** [comment]
This was previously suggested in #3.

**Comment by danielbuechele** [comment]
I tried to enable web inspector bridging it from Obj-C, but I doesn't work for me. Perhaps someone knows help.
- Enable this line to try it: https://github.com/danielbuechele/goofy/blob/master/Goofy/AppDelegate.swift#L71
- See this discussion: http://stackoverflow.com/questions/25200116/how-to-show-the-inspector-within-your-wkwebview-based-desktop-app

**Comment by kalprestito** [comment]
I stumbled upon this one-liner that's supposed to activate it (`defaults write cc.buechele.Goofy WebKitDeveloperExtras -bool true`); but it doesn't work for me, because it apparently needs the app to be sandboxed (http://stackoverflow.com/a/16483200)

**Comment by jklp** [comment]
I also tried using the suggestion in http://stackoverflow.com/questions/25200116/how-to-show-the-inspector-within-your-wkwebview-based-desktop-app by setting the "developerExtrasEnabled" key which does bring up the inspector, but it flickers on and off so you can't actually use it.  

In the end I created another project and enabled the inspector there which seems to work, and it's been what I've been using to debug DOM problems in Goofy.

**Comment by danielbuechele** [comment]
Hm,..I can reproduce this but I have no idea why this is happening.

**Comment by brainlessgit** [comment]
@jklp @danielbuechele you can make windows (view for WKWebView) a little bit smaller, for example 300x300px and call inspector, then it will popup in separate window.
