### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by harrytodorov** [danielbuechele/goofy#171]
<img width="948" alt="screen shot 2015-10-28 at 16 23 22" src="https://cloud.githubusercontent.com/assets/6623554/10793249/578b1a04-7d90-11e5-8259-1b102efd5b7b.png">
Hi there,
I really enjoy your app, but have couple points, that I think would be nice considering.

1) First on the list with conversations you diverse between contacts which have messenger installed and those who haven't. For me personally is more important, if the contact is online at the time or not.

2) When couple of messages are not being sent because of some problem (internet connection etc.), there is a small pop-up, with which you can resend the message when the problem is away. It would be nice, if you could resend all messages at once, when there are couple of them. Not everyone separately.

Greetings,
Harry

**Comment by danielbuechele** [comment]
These are all functions that would need to be provided by messanger.com. Thanks for you feedback, but I won't implement these features on my own, because they will be likely to break on every single change Facebook makes.
