### ISSUE TITLE
Asking for login info on 10.11.1

### ISSUE THREAD

**Issue by Squash019** [danielbuechele/goofy#177]
Hi!

Goofy tells me to submit my login info on 10.11.1, whereas it didn't ask me for any of my info on my MBAir on 10.10.5, it just connected flawlessly. On both cases, I am logged in to my session in messenger.com. Is this a normal behavior on El Capitan?

Thanks in advance!

**Comment by danielbuechele** [comment]
In general the cookie storage is shared between Safari and Goofy. So if you are logged into your account in Safari, Goofy should also be signed in. However, some people had problems with Goofy persisting the login information. Let me know if Goofy keeps logging you out over and over again.

**Comment by Squash019** [comment]
I was talking about a fresh install. With Goofy freshly installed on Yosemite, it didn't ask for credentials, whereas it does ask for them freshly installed on El Capitan,
