### ISSUE TITLE
Notification issue

### ISSUE THREAD

**Issue by monon0ke** [danielbuechele/goofy#181]
Basically my app no longer sends me notifications. It's no longer in my notification centre. I have redownloaded and logged out and even restarted my computer but nothing is working. Please help me it's really infuriating

**Comment by danielbuechele** [comment]
Is it enabled in the notification settings in system preferences?

**Comment by freinbichler** [comment]
I am having the same problem, Goofy does not send notifications anymore. It only makes the sound and updates the badge icon when I receive new messages. Seems to be a general problem.

**Comment by danielbuechele** [comment]
Ok, this seems to be a problem for everyone. Fixes welcome.

**Comment by danielbuechele** [comment]
fixed in latest release

**Comment by redvex** [comment]
Just updated… Preference doesn’t show up now

**Comment by danielbuechele** [comment]
duplicate of #188
