### ISSUE TITLE
When opening application already sent message is visible in input field

### ISSUE THREAD

**Issue by imanel** [danielbuechele/goofy#182]
OS: El Capitan 10.11.1 (15B42)
Goofy: 2.2.3 (927)

Sometimes when I open application it shows message that was already sent in input field. What is strange it's not always the last one - it might also be first before latest one. When I'm clearing input field and restarting application this text is showing again, so it's not any kind of "remember last message typed" (at least not one I know about). If I modify this message (without sending) and restart application still the unedited version is visible.

**Comment by imanel** [comment]
More info: it looks like clearing text field and changing to another conversation fixes this problem, so after restart it will stay empty.

**Comment by raine** [comment]
Seen this as well.
