### ISSUE TITLE
Message from myself bug.

### ISSUE THREAD

**Issue by kamil98** [danielbuechele/goofy#185]
Hi, when I'm sending something from my phone, or via web browser  goofy shows this as a new message (bold font etc.).

**Comment by joallard** [comment]
Indeed, I have the case where often I will get notified of my own messages, even one sent in Goofy. Is there a way we can prevent notification of our own messages?

**Comment by danielbuechele** [comment]
Yes, this is happening for me, too. But I don't have a good idea how to deal with this? The notifications are sent if there is anything in the sidebar written in bold.

**Comment by joallard** [comment]
Ah. I have no idea how Goofy works, but is the sidebar where the information is sourced? Do we have any metadata when "new messages" come in?

**Comment by danielbuechele** [comment]
Yes, I am searching the sidebar for any list-item that is bold and send a notification for it. This bug happens, because my message is marked as unread. But I have no idea how to set/unset the read/unread state.
