### ISSUE TITLE
el capitan - notification center

### ISSUE THREAD

**Issue by redvex** [danielbuechele/goofy#187]
Goofy stops notify me for chat message, in preference it reports: "Activate desktop notification" (even if I've clicked before) and when I click the link, it says me to check browser preferences... 

![schermata 2015-11-23 alle 16 08 30](https://cloud.githubusercontent.com/assets/114123/11340033/7a45929c-91fc-11e5-8de7-18af53a2c01c.png)

**Comment by witali-olszewski** [comment]
same here

**Comment by joallard** [comment]
Possible duplicate of #181
