### ISSUE TITLE
Online friends view

### ISSUE THREAD

**Issue by bliker** [danielbuechele/goofy#19]
One critical things I am missing right now is the online friends view. Before I was using http://flamingo.im and really liked the style they used. I tried to make a mockup...

![online-friends](https://cloud.githubusercontent.com/assets/2674600/7004593/f4484f66-dc6d-11e4-9849-5409910687cd.png)

**Comment by danielbuechele** [comment]
I started working on this, but the sidebar is removed at a certain window size. I am not sure what to do to prevent this. You can check it out on this branch: https://github.com/danielbuechele/goofy/tree/online-state

**Comment by danielbuechele** [comment]
obsolete
