### ISSUE TITLE
Hide notification preview

### ISSUE THREAD

**Issue by luisfontes19** [danielbuechele/goofy#197]
There should be an option to hide the notification preview text

**Comment by danielbuechele** [comment]
Why should there be an option for this?

**Comment by luisfontes19** [comment]
when you are for example showing something on your computer to other people, you don't want them to see the conversation or when you use the app at work, and people  often come to you, its better to see an "You have a new message" than some private conversation :stuck_out_tongue:

**Comment by danielbuechele** [comment]
I don't see this in any other app. You could use Mac OS's do not disturb function.

**Comment by luisfontes19** [comment]
The Messages has it for example... 

![screen shot 2015-12-09 at 09 47 14](https://cloud.githubusercontent.com/assets/5262312/11682047/7e278432-9e5a-11e5-8407-f455154a0ef2.png)

**Comment by danielbuechele** [comment]
Oh wow, never seen that before. I didn't see any option for this in the documentation. Is this private API? Would appreciate any hints in this direction!

**Comment by luisfontes19** [comment]
It's probably a private API since the only apps I have with that option in the notification center are Messages and Mail (haven't noticed this)
But a lot of IM apps implement this in their Settings, a good example its the Messenger app for iOS. I think Telegram is already using it too.

**Comment by rgosain** [comment]
Looks like goofy has one now, whether it always did or it's new - is this resolved?

![goofy notification window](https://cloud.githubusercontent.com/assets/1120897/12058678/58500b94-af1c-11e5-8419-cada98ac2342.png)

**Comment by luisfontes19** [comment]
That's not it...
If you see my print you'll see an option "Show Message Preview"

The message preview is the text that shows when the notification appears. If this options is disabled you'll see instead something like: "You have a new notification" (I thinks that this is not the exact text but you get the ideia)

**Comment by halflings** [comment]
+1 to this, already had a couple bad experiences with messages being shown when I didn't want them to. My solution to this is: Close Goofy. (the "Do not disturb" mode removes ALL notifications and is hard to switch on)
