### ISSUE TITLE
Make use of chitchat app 

### ISSUE THREAD

**Issue by xtensions** [danielbuechele/goofy#212]
Would you consider adding a tab for whatsapp. A single native mac app for whatsapp and messenger would reduce the hassle of opening too many apps. Whatsapp for mac(Chitchat) is already available and is an open source project, so I guess you could use it or may collaborate.  
https://github.com/stonesam92/ChitChat

**Comment by brunorsini** [comment]
I second that, this would be incredibly useful.

**Comment by danielbuechele** [comment]
Nope, sorry. I don't see that in Goofy. You may ask the maintainer of ChitChat.
