### ISSUE TITLE
'"Goofy" would like to control this computer using accessibility features' dialog.

### ISSUE THREAD

**Issue by coreh** [danielbuechele/goofy#213]
Hey there, first of all thanks for taking the time to make this app, it makes using Facebook Messenger way more pleasant.

I was using Goofy today when the following pop up was displayed by OS X:

<img width="573" alt="screen shot 2016-01-16 at 01 10 37" src="https://cloud.githubusercontent.com/assets/418473/12370195/e084b896-bbee-11e5-96f4-f33f50bef041.png">

AFAIK, this is normally shown when an app attempts to call accessibility APIs, like moving other apps's windows, or needs full (global) keyboard access.

What source of special permissions does Goofy need?

**Comment by danielbuechele** [comment]
WTF?! I have no idea where this is coming from. I don't have any feature in Goofy that would require theses privileges. If any one has an idea where this might come from or is having this request, too, I would be happy to know.
