### ISSUE TITLE
Can't paste screenshots or images in clipboard

### ISSUE THREAD

**Issue by sadokx** [danielbuechele/goofy#214]
Pressing CMD + V on the messenger chat does nothing.

**Comment by danielbuechele** [comment]
Can anyone confirm that? It's working here.

**Comment by confuser** [comment]
Copying from a word document, `CMD + V` doesn't paste, current work around is to right click and select paste. However, copying from an editor like Sublime Text works absolutely fine.

**Comment by aboolean** [comment]
I'm experiencing the same issue in the current version (2.2.5).

I've tried the following:
- pasting an image file copied from Finder
- pasting/dragging an image from Chrome/Safari (dragging from Safari results in a URL path)
- pasting pixels from screenshot/Preview
