### ISSUE TITLE
Notification Shows Incorrect Avatar

### ISSUE THREAD

**Issue by MsQueen** [danielbuechele/goofy#217]
Using Goofy 2.2.5, El Capitan 10.11.2:

Notifications are turned on and when I receive a messenger notification, it shows an incorrect avatar for that message. It will show the avatar of the most recent unread message of an individual person (excludes group chats).

**Comment by auszone** [comment]
+1

**Comment by igorlopasovsky** [comment]
+1

**Comment by danielbuechele** [comment]
fixed in f709427
