### ISSUE TITLE
Bug layout CSS

### ISSUE THREAD

**Issue by adrianoresende** [danielbuechele/goofy#22]
![image](https://cloud.githubusercontent.com/assets/798755/7046679/eff4b0b4-dddd-11e4-86ed-25e951e2fc94.png)

**Comment by danielbuechele** [comment]
Can not reproduce this. Are you on the latest version (1.2.5)?

**Comment by kalprestito** [comment]
To reproduce it, open Goofy in expanded mode, search for a conversation (left search bar) and collapse Goofy.

**Comment by adrianoresende** [comment]
Was in version (1.2.4) but after update and now is this way:
![image](https://cloud.githubusercontent.com/assets/798755/7049066/200628aa-dded-11e4-8c05-96ed4d7aac1b.png)

**Comment by kalprestito** [comment]
It's not the upgrade that affected that, but the number of results the search spawned. Try resizing the window until the left sidebar expands, clear the left search bar and resize it again until it collapses. Does it still happen?

**Comment by adrianoresende** [comment]
@kalprestito i clear search but continues the error CSS.

OBS: My facebook language is brazilian

**Comment by kalprestito** [comment]
Can you take a screenshot in the expanded mode?

**Comment by adrianoresende** [comment]
@kalprestito 
![image](https://cloud.githubusercontent.com/assets/798755/7049185/084c184a-ddee-11e4-8d5f-f61ed50ed94a.png)

**Comment by kalprestito** [comment]
I can see a blank space to the right of the sidebar (as the blue shade for the selected conversation does not expand to the split), it'd seem that's what causing it. However, it doesn't show up for me, so I've got no way of fixing it.

Damn you and your A/B testing, Facebook!

**Comment by kalprestito** [comment]
I tried setting my Facebook language to Portuguese (Brazilian), but it doesn't show up for me

**Comment by adrianoresende** [comment]
This blank space is scroll actived for my macbook pro hahaha

![image](https://cloud.githubusercontent.com/assets/798755/7050033/c50cbbd2-ddf4-11e4-854d-3a2e23522dc4.png)

**Comment by adrianoresende** [comment]
Well, Swift or Objective C check if user have scroll actived?

**Comment by kalprestito** [comment]
Ahhh okay, it is so. Steps to replicate, then:

1. Enable `Always visible` scrollbars in `System Preferences` > `General`
2. Collapse Goofy
3. Scrollbar creates visual artifacts

Gonna create a new issue with the collapsing search problem

**Comment by danielbuechele** [comment]
obsolete
