### ISSUE TITLE
emoticon o.O is missing

### ISSUE THREAD

**Issue by dwoznicka** [danielbuechele/goofy#220]
the input "o.O" turns out as the same emoticon as ":\" which is somehow problematic, sometimes. i.e. facebook users(non-goofy) see/use them in different purposes. 
if it's not possible to add another emoticon for o.O (hopefully similar to facebook's) please make it not-convert itself to the uncorrect emoticon :)

(version 2.2.5 (961) )

**Comment by mcescalante** [comment]
both O.o and o.O render the proper smiley for me in 2.2.5 with OSX 10.11.2

**Comment by danielbuechele** [comment]
yes this was fixed in the last release. Thanks for pointing out!
