### ISSUE TITLE
Sparkle

### ISSUE THREAD

**Issue by kenrossi** [danielbuechele/goofy#223]
http://arstechnica.com/security/2016/02/huge-number-of-mac-apps-vulnerable-to-hijacking-and-a-fix-is-elusive/  

Please update sparkle when you get the chance. Currently it's 1.10.0

**Comment by danielbuechele** [comment]
From what I read Goofy doesn't seem to be affected, because all communication is sent over HTTPS. However, I'll update Sparkle. Thanks for reporting this!

**Comment by kenrossi** [comment]
Thanks for responding so quickly. This is what I am getting as updates from other apps "Fixes a vulnerability in the updater by now delivering all updates over https" I don't think it has to do with your communication layer from goofy to FB servers. I think it has to do with the update mechanism for your app.

**Comment by danielbuechele** [comment]
Yes, the other apps switched from delivering their updates via HTTP to HTTPS. But as you can see here https://github.com/danielbuechele/goofy/blob/master/Goofy/Info.plist#L45 the updates in Goofy are already delivered via HTTPS. So Goofy is not vulnerable to this.
