### ISSUE TITLE
Last time active not being refreshed

### ISSUE THREAD

**Issue by radzik07** [danielbuechele/goofy#225]
After an hour or so the "active" indicator under the name does not refresh. I have to CMD+R to see the  user's real last active time or log in to facebook via browser.

**Comment by yangbrian** [comment]
I believe this is an issue with Messenger.com in general. The same issue happens if you use the website in a browser.

**Comment by danielbuechele** [comment]
When same things happen at messenger.com Goofy can not do anything about this.
