### ISSUE TITLE
Add support for Retina Display 

### ISSUE THREAD

**Issue by dontuncleme** [danielbuechele/goofy#226]
Hi. The app looks a little bit weird in my Retina Display. I think it's not so difficult to make the [icons](https://monosnap.com/file/bIEfuyOMlcoE3DzYJNFFYl5mUBxWas) with a bigger size to adapt the app for the Retina Display resolution.
Thanks in advance.

**Comment by danielbuechele** [comment]
All buttons provided by Goofy are available in retina-resolution. But I also see that sometimes Facebook is not getting the retina assets for their buttons. A restart of the application sometimes helps.
However, there is nothing I can do about this.
