### ISSUE TITLE
Insert emoticons

### ISSUE THREAD

**Issue by filipefigcorreia** [danielbuechele/goofy#227]
I have a suggestion for a feature: show a small keyboard-like panel in the bottom of the window, to would allow to insert [emoticons](http://www.symbols-n-emoticons.com/p/facebook-emoticons-list.html).

**Comment by danielbuechele** [comment]
CTRL+CMD+SPACE brings up Mac OS default emoji picker, which should be sufficient.

**Comment by filipefigcorreia** [comment]
Works great!
