### ISSUE TITLE
some bugs notices

### ISSUE THREAD

**Issue by mjgritli** [danielbuechele/goofy#230]
**Hello dear developer**
i've been using this app for a while and i love it, but during so, i noticed some bugs...
- when receiving a new Message Request, you can't go back to normal Messages , you have to restart the app.
-  when trying to send files/images , after the windows appears to select a file, if you click on am image and then press the space bar to preview before sending, the windows goes back to background automatically and you have to open a new one.
-  when typing and switching between languages , sometimes you can't delete what you typed, you have to select another chat and then go back to be able to erase the worlds and type new ones to send .

other than that... you app is awesome 

> Good Luck fixing the issues.

Mohammed Gritli
Cisco CCNP R&S, Cisco CCNA Sec, Microsoft MCSA.
Android Developer, iOS Developer, web Developer .

**Comment by joallard** [comment]
To make this easy for the maintainers to process this, I think you should file a ticket for every issue encountered and search to see if this hasn't been reported already.
