### ISSUE TITLE
Notifications stopped working

### ISSUE THREAD

**Issue by yangbrian** [danielbuechele/goofy#231]
Notifications seem to have stopped working as of mid-day yesterday (worked in the morning). The sound and dock icon badge still occur but the notification itself no longer gets sent (nor does it appear in the notification center).

I tried rebooting, signing out, and reinstalling Goofy. The desktop notifications setting is set to On.

Because I reinstalled Goofy and it hasn't sent any notifications since, it no longer appears in my Mac's notifications settings.

Goofy 2.2.5 (961)
Mac OS X 10.11.3

**Comment by neilio** [comment]
I've seen this too.
