### ISSUE TITLE
No notifications for muted conversations

### ISSUE THREAD

**Issue by fossil12** [danielbuechele/goofy#233]
The system notifications for new messages are great, but it would be nice to get no notifications when a conversation is muted.

**Comment by danielbuechele** [comment]
This feature is implemented, but it may be broken again due to changes from Facebook. https://github.com/danielbuechele/goofy/blob/master/server/src/fb.js#L205 Should check if a conversation is muted.

**Comment by fossil12** [comment]
I see. Then it looks like it's broken for group chats at least.

**Comment by joallard** [comment]
@danielbuechele That's weird because `._569x ._56ck` is still the right selector, but I still get the bug. (2.2.5) – Oh, maybe because the fix is unreleased? Looks like it's master-only.

**Comment by danielbuechele** [comment]
fixed in f709427
