### ISSUE TITLE
Cmd+Shift+[ and Cmd+Shift+] to switch conversations?

### ISSUE THREAD

**Issue by vartan** [danielbuechele/goofy#234]
It would be nice to match the native OS X Messages client to be able to switch conversations with the keyboard shortcut

**Comment by danielbuechele** [comment]
It can be done using `CMD+[` which is the same for me in Messages.app.

**Comment by vartan** [comment]
Wow that was such a fast response. The reason I am used to the shift version is because it's also to switch tabs.

Thanks.

Originally I was gonna make a pull request that the images weren't showing up as Retina. I checked messenger.com on chrome and saw they were retina, but then checked on safari and saw the same non-retina images. Not your problem :)

**Comment by danielbuechele** [comment]
Cool. You can overwrite Goofy's default shortcuts using System Preferences, if you like.
