### ISSUE TITLE
Can't send pictures

### ISSUE THREAD

**Issue by paolobozzelli** [danielbuechele/goofy#237]
When trying to send a picture from the client, I am not able to send it after file selection, either I double-click on the file or I select the file and then click on **Open** button.

**Comment by joallard** [comment]
Confirmed. STR:

1. Open conversation
2. Click Add Files button
3. Select picture
4. Click Open

Expected: Photo is attached to conversation
Actual: Nothing happens.

**Comment by danielbuechele** [comment]
Can not reproduce. Please let me know if it still doesn't work for you. Closing for now.

**Comment by joallard** [comment]
Hmm. I can still reproduce it. OS X 10.10.5, Safari 9.1.1. I wonder why.

**Comment by paolobozzelli** [comment]
With Version 2.2.5 (961), on Mac OS X 10.11.5, it now works fine by:
- Clicking on the image button;
- Selecting a picture;
- Clicking "Open".

**Comment by joallard** [comment]
Well yeah, by reproducing the steps to reproduce. Anyway, it probably fixes itself in 10.11.
