### ISSUE TITLE
GIF not getting sent to the correct recipient

### ISSUE THREAD

**Issue by oluwasayo** [danielbuechele/goofy#239]
Steps to reproduce:
1. Get on a slow network.
2. Open a conversation (conversation A) and use the GIF feature to send a GIF.
3. While Goofy is loading GIF, switch to another conversation (conversation B).

GIF gets sent to conversation B.

**Comment by joallard** [comment]
Confirmed. 

STR in absence of slow network:

1. Open conversation and GIF pane, do not select a GIF yet.
2. Leave GIF pane open, turn off network connection. (No internet warning is normal)
3. Click a GIF, nothing happens.
4. Switch to conversation B.
5. Turn on connection.

Actual: GIF is sent to B.
Expected: GIF is sent to A.

**Comment by danielbuechele** [comment]
@joallard thanks for helping to clean up the issues a little.

**Comment by joallard** [comment]
@danielbuechele No problem, it's always easier to drive-by help repos maintained by others rather than tackle the pile of work I have to do on selectize/selectize ;o) Besides, I know how it feels to get buried under a pile of various untriaged issues. Cheers!
