### ISSUE TITLE
Collapsing while searching in the sidebar creates visual artifacts

### ISSUE THREAD

**Issue by kalprestito** [danielbuechele/goofy#24]
When searching for a conversation
![documento_skitch_en_blanco](https://cloud.githubusercontent.com/assets/511681/7050367/3e298e6a-de21-11e4-8a26-686e1827abf2.png)

When collapsed
![documento_skitch_en_blanco](https://cloud.githubusercontent.com/assets/511681/7050385/5fccdf4a-de21-11e4-9975-7f6994e2cc5e.png)

Even more gruesome when the results are shorter than the window
![documento_skitch_en_blanco](https://cloud.githubusercontent.com/assets/511681/7050405/7d66c700-de21-11e4-827b-07a89fc17888.png)

And in its worst when showing no results at all
![documento_skitch_en_blanco](https://cloud.githubusercontent.com/assets/511681/7050469/c45ba20c-de21-11e4-96a7-3160dacb6d67.png)

(First discovered in #22)

**Comment by danielbuechele** [comment]
obsolete
