### ISSUE TITLE
Mute notifications not working

### ISSUE THREAD

**Issue by guptapriyanka** [danielbuechele/goofy#242]
The mute notifications for a group isn't working. Still getting notifications even when the thread is muted

**Comment by joallard** [comment]
Thank you. Looks like a duplicate to #233

**Comment by danielbuechele** [comment]
fixed in f709427

**Comment by joallard** [comment]
Thanks @danielbuechele . Just to make sure, the line was changed to `MUTED = '_569x';`, no dot for class selection. Am I missing something or was that unintentional?

**Comment by danielbuechele** [comment]
This is intentional, because this class is not used within a query selector, but `classlist.contains()`

**Comment by joallard** [comment]
Ah right, cool then, thanks!
