### ISSUE TITLE
Typing Domain Replaces All Other Text

### ISSUE THREAD

**Issue by StanfordAlan** [danielbuechele/goofy#243]
If I type a domain and then press a key after the ending (space, comma, semicolon, period, question mark exclamation point, parenthesis, etc., but **not** letters or numerals), the remaining text is wiped out and replaced only by the domain. 

**Example**
**Typed:** Have you seen google.com?
**After pressing the ? key:** google.com

Also, the cursor always moves between the first and second letters, in the example the G and the first O.
This is reproducible and always happens on both of my Macs. This has only been in the last version or two (maybe three); it was not in the earlier versions. 

Thank you.

**Comment by joallard** [comment]
Tried on 2.2.5 with OSX 10.10.5:

1. Type "Have you seen google.com"
2. Type "?"

Nothing unexpected happens. Does your issue happen on messenger.com?

**Comment by StanfordAlan** [comment]
It does not happen on messenger.com, only in the Goofy app. I have made sure thing is running on my system that might be replacing the text. 

Goofy 2.2.5
Mac OS X 10.11.4

Maybe the OS makes the difference.

Thanks.

**Comment by StanfordAlan** [comment]
Have been able to test it on an updated OS?

**Comment by joallard** [comment]
Maybe someone else with OSX 10.11 could try

**Comment by Jactaen** [comment]
Tested with 10.11.4 - not possible to replicate

**Comment by joallard** [comment]
Retried in 2.2.6 and OSX 10.11.6, no repro.
