### ISSUE TITLE
Goofy does not 'remember' Menu Bar state

### ISSUE THREAD

**Issue by DanielNeville** [danielbuechele/goofy#245]
Hello,

When exiting and re-opening Goofy, it will not store the Menu Bar state.

Is this intentional behaviour?  Would it be possible to pass a command line flag or similar to ensure the Menu Bar icon is always active?

Kind regards.

**Comment by joallard** [comment]
Not really sure what you mean by the "Menu bar" and what attribute exactly you're aiming to (width? scroll height?), but I'm pessimistic on this enhancement being practically doable for the project.

**Comment by PrinceBalabis** [comment]
I really love this app but this is the only reason I'm not using it.
I want a messenger app that always starts on boot, and shows a tiny menu bar icon. I always want to easily be able to click on the menu bar and it should open the messenger window, but this feature never has been working for me. When the app starts, you always have to manually toggle on the menu bar item. And when it is enabled, when i close the main window, and click the menu bar item, nothing happens. What is the point of having a menu bar item if it does nothing?
