### ISSUE TITLE
Use messenger.com

### ISSUE THREAD

**Issue by MattFaluotico** [danielbuechele/goofy#25]
Much more modernized css.

**Comment by danielbuechele** [comment]
Yes! I steady started working on this!

**Comment by bliker** [comment]
It looks modern but not very practical. So much useless whitespace and that bright blue :hurtrealbad: ...

**Comment by peterjosling** [comment]
And doesn't support drag and drop file uploads either... :(

**Comment by stianjensen** [comment]
And on large screens, the bubbles get separated very far to the left and right.

**Comment by danielbuechele** [comment]
done

**Comment by lukasschwab** [comment]
+1 to @bliker @peterjosling @stianjensen !

@danielbuechele I mentioned this on Twitter, but one of the primary reasons I use Goofy is that I prefer your UI to that produced by Facebook.

Goofy had all the functionality of the timeline-style messenger app, but in a much better UI in a separate application. I would love to see you wrap the Messenger CSS with your own, just as you did before; not a fan of the messages on alternating sides, of the amount of whitespace (especially on high-resolution monitors), and I would love to have the old "press enter to send message" check box back.

I love your app more than Facebook. Really hoping to see it again :)
