### ISSUE TITLE
Browser doesn't support video calls

### ISSUE THREAD

**Issue by DotTheI** [danielbuechele/goofy#250]
![2016-06-03 16 49 25](https://cloud.githubusercontent.com/assets/10737439/15780898/c6d18b66-29b4-11e6-98c8-87210cb64728.png)

**Comment by iBobik** [comment]
At first we need to have WebRTC support in Webkit. (Do Messanger need also other features?) Current progress: https://bugs.webkit.org/show_bug.cgi?id=124288

Then we will see if FB will add Safari to supported browsers. If not it will be needed to mimic Chrome.

**Comment by iBobik** [comment]
@danielbuechele Is it fixed? I see no referenced commit neither call icon is not visible in the app release.

**Comment by danielbuechele** [comment]
Sorry. This is not fixed. However with the switch to electron it would now be possible to support calls. However, this is currently not on my roadmap for the near future. If anyone want's to jump on this, feel free.

**Comment by maryokhin** [comment]
Now that the app is running on Electron it should be possible. What would the procedure be for anyone who is interested in looking into this? Wiresharking the web version of messenger.com to figure how exactly it uses WebRTC and then trying to replicate?

**Comment by jklp** [comment]
Added in v3.4.1
