### ISSUE TITLE
Something wrong with like button if I hovered

### ISSUE THREAD

**Issue by csakiistvan** [danielbuechele/goofy#252]
Something wrong with like button, if I hovered its recolor to orange, and it has a big area and its background is orange color.

![goofy_orange](https://cloud.githubusercontent.com/assets/2457274/16074506/140f49d8-32eb-11e6-8b06-b9b8eb9c65b0.gif)

**Comment by joallard** [comment]
My like button doesn't go orange when I hover it. Weird.

**Comment by ErikUu** [comment]
Having the exact same issue.
