### ISSUE TITLE
OSX app shortcuts don't work

### ISSUE THREAD

**Issue by Chubacca** [danielbuechele/goofy#253]
OSX app shortcuts as detailed here do not work:

https://support.apple.com/kb/PH18418?locale=en_US

The shortcuts show up in the menu, but they don't actually work in app. It'd be great to have either the ability to change the shortcuts in app, or make it compatible with app shortcuts. Thanks!

**Comment by danielbuechele** [comment]
All keyboard shortcuts from the menu are working for me. Which shortcuts don't work for you? Closing for now.

**Comment by Chubacca** [comment]
I attached a screenshot of my settings. I modified the shortcuts, and they do not work. They work with their original settings.

<img width="529" alt="screen shot 2016-06-27 at 7 55 36 pm" src="https://cloud.githubusercontent.com/assets/196094/16402402/28b22a6c-3ca1-11e6-9ec8-743ea67fdab9.png">
