### ISSUE TITLE
How to access message requests? 

### ISSUE THREAD

**Issue by rcross** [danielbuechele/goofy#254]
Is there a way to access message requests from the regular interface? I can't seem to find anything, though I've seen a comment about people not being able to see the back button once they do access them.

**Comment by joallard** [comment]
There is not at the moment, I'd call it an enhancement. It's pretty much the as #238, we don't show the space where the button to either access MR or come back from it.

**Comment by rcross** [comment]
Do you want a new issue opened to track it as an enhancement? Any idea when it might get implemented?

**Comment by joallard** [comment]
No idea, but what I do know is that in projects maintained on spare time, pull requests can go a long way. Otherwise, @danielbuechele is very probably aware of it, but it might not be the no.1 priority.
