### ISSUE TITLE
Several app elements do not have high res retina graphics

### ISSUE THREAD

**Issue by Komodovaran** [danielbuechele/goofy#257]
Except for text, animated stickers (only when moused over) and the blue icons in the top toolbar, everything else lacks high res graphics. The messenger.com web version fully supports it though.

Adding retina capabilities in the plist doesn't seem to make a difference.

Running 10.11.5.

**Comment by gklka** [comment]
<img width="765" alt="screen shot 2016-07-09 at 19 48 12" src="https://cloud.githubusercontent.com/assets/866694/16709339/2560aef8-460e-11e6-926b-1b4d863f815a.png">

**Comment by gklka** [comment]
Messenger.com has retina graphics:
<img width="763" alt="screen shot 2016-07-09 at 20 00 34" src="https://cloud.githubusercontent.com/assets/866694/16709383/df14151e-460f-11e6-8d62-3d901fa762fa.png">

**Comment by gklka** [comment]
It seems that messenger.com has fixed the issue, so you can close this ticket.
