### ISSUE TITLE
Settings layout is broken

### ISSUE THREAD

**Issue by gklka** [danielbuechele/goofy#259]
Goofy's custom CSS breaks Messenger's settings layout:

![screen shot 2016-07-09 at 19 46 14](https://cloud.githubusercontent.com/assets/866694/16709335/f740788c-460d-11e6-849e-b9f5d6a743e3.png)
![screen shot 2016-07-09 at 19 46 16](https://cloud.githubusercontent.com/assets/866694/16709334/f74050e6-460d-11e6-8570-5e34e16bd276.png)

**Comment by euklides** [comment]
I can't change nicknames anymore. The text ends up in the chat window even though you've selected the input box for nickname.
