### ISSUE TITLE
Standalone messenger.com

### ISSUE THREAD

**Issue by sebj** [danielbuechele/goofy#26]
You can now access Facebook Messenger alone via [messenger.com](https://www.messenger.com), which seems to be styled similar to the Facebook Messenger iOS and Android apps (and might look more at home on Yosemite?)

Just thought I should mention whether you'd consider switching to that as the base URL, seeing as it would probably be lighter in terms of size and better styled (arguably).

**Comment by sebj** [comment]
And as I publish this, I refresh the issues page and notice someone else has already posted this issue.. :grin:

**Comment by danielbuechele** [comment]
Duplicate of #25
