### ISSUE TITLE
Conversation Shared Photos issue

### ISSUE THREAD

**Issue by Quik7** [danielbuechele/goofy#264]
![zrzut ekranu 2016-07-11 o 13 20 20](https://cloud.githubusercontent.com/assets/14108143/16729036/4468f12c-476a-11e6-93f6-90a667aa877b.png)

Conversation photos from conversation Info still not working. I can't browse shared photos from your app.

**Comment by joallard** [comment]
Confirming in 2.2.6

**Comment by generator85** [comment]
I also notice that this problems causes a lot of lag when typing a message in my largest group chat. Hiding the section fixes this.
