### ISSUE TITLE
Input lag when typing a message

### ISSUE THREAD

**Issue by sayzenberg** [danielbuechele/goofy#267]
I have permanent input lag when entering a message into the message box in my chats. The cursor and the rendering of characters isn't keeping up with my actual typing. Restarting the app doesn't help; it launches and has the same level of lag at startup.

**Comment by yangbrian** [comment]
I've noticed this too since around the middle of last week.

**Comment by Shikkic** [comment]
+1 This happened somewhat recently and has made Goofy totally usable

**Comment by euklides** [comment]
Me too.

**Comment by broketheinterweb** [comment]
Experienced this for the first time today, restarting the app fixed it. App takes a few whole seconds to close entirely or the same instance stays open and the issue is still there.

**Comment by euklides** [comment]
When it happens it's (possibly) only in chats with custom colours.

**Comment by Shikkic** [comment]
@euklides I think you're right. I had changed the custom color back to the default blue and it works great again.

**Comment by broketheinterweb** [comment]
I second this. Person I was chatting with changed the colors before this started happening.

**Comment by Shikkic** [comment]
It's not as snappy as I would like it to be. However, definitely way more usable.

**Comment by euklides** [comment]
Oddly enough, to me it seems like the level of lag varies and is only present sometimes. At times it's not there, other times barely tolerable, other times it's so slow you have to sit and wait a few seconds for the text to catch up if you write a few sentences.

**Comment by sayzenberg** [comment]
Yeah, seems that it only happens on chats with custom colors for me as well. It also appears to be unrelated to any recent commits. Old commits and old releases seem to have the same issue.

**Comment by igorlopasovsky** [comment]
+1. Issue disappeared after I changed chat colour to its default value
