### ISSUE TITLE
Text input gets wonky after a few hours of having the app open

### ISSUE THREAD

**Issue by broketheinterweb** [danielbuechele/goofy#268]
OS X 10.11.6

Been seeing this problem for several weeks on and off. Not quite the same as the lag issue-- backspace stops working and I believe cmd+a also fails at this point. Requires restarting the app but takes a few seconds for the app to close completely, otherwise the same offending instance appears to remain open and the issue persists.

**Comment by samlehman** [comment]
I too get this issue.  letters get jumbled sometimes.

It started lagging, I typed `should be still there <enter>`, and it shows up in the chat log as 

```
st
hould be sill there
```

I think the s from should and t from still got separated from the original line?
