### ISSUE TITLE
Clicking the settings icon makes the screen white (messenger.com)

### ISSUE THREAD

**Issue by RvMouche** [danielbuechele/goofy#27]
If I click on the settings icon this happens (using the latest download Daniel tweeted)
![screen shot 2015-04-09 at 13 49 40](https://cloud.githubusercontent.com/assets/2125224/7066110/6e4648a6-debf-11e4-92ef-7a1c8b8cd7a1.png)

**Comment by danielbuechele** [comment]
Can you help me to reproduce this? Not happening here.

**Comment by RvMouche** [comment]
Tried to reproduce again (it kept doing that this morning) but it works
now. Weird

**Comment by bradpurchase** [comment]
I can't seem to get this *not* to happen. Just get a white screen, and then I have to cmd+r to refresh and get the main app window back.

**Comment by RvMouche** [comment]
Just had the white screen again, but got it when I clicked on a photo - weird.

**Comment by danielbuechele** [comment]
Now it is happening to me, too. I'll check this out later.

On 09.04.2015, at 20:30, Raimond van Mouche <notifications@github.com>
wrote:

Just had the white screen again, but got it when I clicked on a photo -
weird.

—
Reply to this email directly or view it on GitHub
<https://github.com/danielbuechele/goofy/issues/27#issuecomment-91319764>.

**Comment by RvMouche** [comment]
Addition: also the stickers store makes it white

**Comment by stianjensen** [comment]
The same thing happens when opening photos for me

**Comment by danielbuechele** [comment]
fixed
