### ISSUE TITLE
Broken layout

### ISSUE THREAD

**Issue by xxdavid** [danielbuechele/goofy#270]
Today, I and my friend began to experience an issue with Goofy. The layout is completely broken. It's like if it didn't apply the custom CSS. The interesting thing is that when I compiled Goofy from source, it's working. The normal production version is 2.2.6 but the one from source is 2.2.5. Did you only forgot to push an update of [Info.plist](https://github.com/danielbuechele/goofy/blob/master/Goofy/Info.plist#L20) or are there any other differences?

I attach a screenshot. Production version (2.2.6) is in the background and the compiled one (2.2.5) in the foreground.
![Version comparison](https://cloud.githubusercontent.com/assets/3393339/17837558/77b6b4bc-67b6-11e6-992b-18476b044dd4.png)

**Comment by danielbuechele** [comment]
The server hosting the custom CSS file had some trouble today. Should be working again...
