### ISSUE TITLE
OS X Share Extension

### ISSUE THREAD

**Issue by Calorion** [danielbuechele/goofy#274]
Please include a Mac OS X Share Extension with Goofy, so that you can share webpages and the like in Facebook Messenger.

**Comment by simardcasanova** [comment]
That would be awesome!

**Comment by gklka** [comment]
I don't think this would be useful. It's so easy on macOS to just copy and paste the address.

**Comment by Calorion** [comment]
That’s equally true for every Safari extension, and yet they’re still useful.

Here’s the steps for copying and pasting: 

1. Hit Command-L to enter the address field.
2. Hit Command-C to copy the address.
3. Find Goofy.
4. Launch Goofy. 
5. Wait for Goofy to load.
6. Choose a recipient.
7. Paste the URL into the appropriate conversation in Goofy.
8. Write whatever other text you wish to add, and hit Return.

Here’s the steps for using a Safari extension:

1. Click on the Extensions menu. 
2. Click on Goofy.
3. Select a recipient.
4. Add whatever text you want, and click Send.

It may seem trivial to eliminate four steps, but that’s half of them, and is significantly more convenient (especially the elimination of 3, 4 and 5).

**Comment by danielbuechele** [comment]
I agree on this and think it would be a great addition to Goofy. However, I need to see if I have time to implement that. PRs are welcome of course!

**Comment by Calorion** [comment]
Closed…why?
