### ISSUE TITLE
Contact names disappear at wrong breakpoint

### ISSUE THREAD

**Issue by jono-hayward** [danielbuechele/goofy#283]
I have noticed that when the Goofy window is between 640 and 800 pixels wide, the sidebar seems to snap to the compact layout that only shows contact pictures but no names, while the rest of the window remains in the full layout:

![image](https://cloud.githubusercontent.com/assets/659408/19227605/f5a4402e-8f07-11e6-96f8-88dfa7f95cc0.png)

I suspect this could be a bug related to MacOS Sierra, as it's happening on my (updated) machine but not a colleague's machine still running Yosemite.

System information:
macOS Sierra 10.12
iMac (27-inch, Late 2013), 3.2 GHz Core i5, 16gb memory

**Comment by danielbuechele** [comment]
Duplicate
