### ISSUE TITLE
Goofy no longer displays chat names

### ISSUE THREAD

**Issue by killersquirrel59** [danielbuechele/goofy#285]
Out of nowhere tonight my Goofy app, which has not worked flawlessly, but has worked up until now, suddenly stopped displaying any of the names of my chats or contacts, just displaying the avatar image and a blank space. The app did not update, and when deleted and reinstalled the problem persisted. I have no idea what could be causing this, but I would dearly like it fixed.

<img width="349" alt="screen shot 2016-10-11 at 11 25 43 pm" src="https://cloud.githubusercontent.com/assets/22786033/19299599/2aaf51fc-900a-11e6-8898-7d9a33838624.png">

**Comment by danielbuechele** [comment]
Hm,…
this is dependant on the size of the window. If you make the window larger, the name get visible again. However, this should be fixed.

**Comment by unremarkablegarden** [comment]
I guess messenger.com changed. The names have started folding in to be just pics at a certain size.
