### ISSUE TITLE
Backspace stops working randomly

### ISSUE THREAD

**Issue by theheron** [danielbuechele/goofy#292]
Sometimes the backspace key stops working. I can type and add text, but cannot delete it. Restarting the app fixes the issue.

rMPB 13" (2015), MacOS Sierra 10.12, app version 2.2.6 (973).

Not sure if there's anything else I should add. 

EDIT: backspace key keeps working in other apps.

**Comment by yangbrian** [comment]
I have the same issue on macOS Sierra (and El Capitan too), although it gets fixed once I navigate to another chat and come back. No restarting necessary. It happens maybe once or twice a day and randomly.

**Comment by mcescalante** [comment]
I've had this issue maybe once a week or so and there isn't an obvious behavior that triggers it. When I do have the issue I just reload with `⌘ + R` which isn't a problem at all

**Comment by andremiguelaa** [comment]
I have this problem randomly too, my workaround is to select a chat with another person/group and return to the initial chat.
