### ISSUE TITLE
Easy way to inject and test custom javascripts

### ISSUE THREAD

**Issue by d4rky-pl** [danielbuechele/goofy#3]
It'd be nice if you either create a way, or if there already is one just describe it in README, to add custom JS and test it without recompiling whole app.

If it's too much to ask for, just enable Inspector in WKWebView (either by default or when some kind of preference or runtime option is passed) :)

**Comment by danielbuechele** [comment]
When compiling the Swift project locally, a local JS-file is used. See https://github.com/danielbuechele/goofy/blob/master/Goofy/AppDelegate.swift#L43
But adding a hidden preference or something to change the path of the JS-file would also be nice!

**Comment by d4rky-pl** [comment]
I'm not sure if it's a good idea to keep .js files on external server, especially unversioned. If you ever switch from AWS to something else, everyone will have a very bad time :)

**Comment by danielbuechele** [comment]
Loading the JS from an external server is super convenient for responding to changes on Facebook's side and quickly adding features. However, linking to a domain that I control and introducing version would make sense.

**Comment by d4rky-pl** [comment]
Then I guess there're two issues here:

[ ] moving away from AWS domain and into something like static.goofyapp.com
[ ] adding either advanced preference or `--option` to inject custom CSS/JS for debugging and development reasons

**Comment by danielbuechele** [comment]
In the current version you can set a custom URL for the JS in Goofy's `Info.plist` using `GoofyJavaScriptURL`

**Comment by danielbuechele** [comment]
The JS-file is now served from another host. There can be specific versions of the JS-file and there is a fallback if there is not JS-file for this specific version.
