### ISSUE TITLE
Attach image button doesn't work

### ISSUE THREAD

**Issue by podgib** [danielbuechele/goofy#30]
Clicking the image attachment button in the messenger.com version doesn't do anything. No file chooser dialogue pops up.

**Comment by lukasschwab** [comment]
Button now appears gone altogether––would love to see this functionality!
![screen shot 2015-04-09 at 5 35 13 pm](https://cloud.githubusercontent.com/assets/4955943/7079888/100bf478-dedf-11e4-8197-8887ad66d56f.png)
