### ISSUE TITLE
Workplace

### ISSUE THREAD

**Issue by lanceplaine** [danielbuechele/goofy#303]
Hi,

Are you planning on making this project compatible with [Workplace](https://workplace.fb.com/workchat/)?

Thanks

**Comment by danielbuechele** [comment]
yes, I am working on this.

**Comment by lanceplaine** [comment]
Great!
If you need help to beta-test the feature feel free to reach me out :)

**Comment by lanceplaine** [comment]
@danielbuechele: I just saw that Workchat has now a dedicated URL (In my case `https://talentoday.facebook.com/chat`).
Maybe it make it easier now to make it compatible with Workchat.

**Comment by lanceplaine** [comment]
Thanks!
