### ISSUE TITLE
Goofy adds media controls to the Touch Bar

### ISSUE THREAD

**Issue by LanderN** [danielbuechele/goofy#304]
Goofy triggers a media control to be added to the touch bar when the new message sound is played. This doesn't disappear until Goofy is stopped.

![](http://i.imgur.com/MjyO1KZ.png)

Tapping the play icon plays the new message sound.

**Comment by m-spry** [comment]
Adding on to this in my experience Goofy also takes control of the media controls.

If you have iTunes playing, pause it and if a Goofy notification comes through it will take priority. When you press the play button again it will loop the Goofy notification sound rather then resuming iTunes.

Also using a 15 Inch 2016 pro
