### ISSUE TITLE
Move to electron-based app

### ISSUE THREAD

**Issue by danielbuechele** [danielbuechele/goofy#307]
For version 3 Goofy will move to an [electron](https://github.com/electron/electron)-based architecture. This means basically all code in this repo will be replaced with the new version.

This decision will hopefully bring some major advantages:
- As electron is based on Chromium, we can add support for call
- Windows and Linux support is possible
- Hopefully some of the weird bugs will vanish
- Not requiring Xcode will potentially allow a bigger developer base to contribute on this project

I started working on [Goofy for Work](http://github.com/danielbuechele/GoofyForWork), a version of Goofy to use with Workplace by Facebook. This version is already based on electron and coming along pretty good. Most of the codebase will be shared between Goofy and Goofy for Work.

However, this means all the issues labeled with version 2, will not be addressed, as I focus on version 3. Once this version is released, I will close these issues.

**Comment by Etheryte** [comment]
When will you add a branch for the electron version? Getting some early testers and/or contributors on board would allow for both the work to be finished faster and for bugs to be caught early.

**Comment by danielbuechele** [comment]
I hope I can add a branch for this in the next couple of days.

**Comment by martinwolf** [comment]
If you need a beta tester, let me know!

**Comment by kevingelion** [comment]
Looking forward to helping out :)

**Comment by danielbuechele** [comment]
I published a branch called `electron` yesterday. Aiming for a first release today.

**Comment by kevingelion** [comment]
Awesome! Happy to see you're using nuts for updates 😄

**Comment by danielbuechele** [comment]
As of now, the branch is merged into master.

**Comment by danielbuechele** [comment]
I just released v3. Closing this issue.
