### ISSUE TITLE
Add Github topics after v3 release.

### ISSUE THREAD

**Issue by Etheryte** [danielbuechele/goofy#309]
After the new, electron-based platform has its initial release, it seems like a logical move to add [Github tags (called "topics")](https://github.com/blog/2309-introducing-topics) to the project.  
The benefits may include increased visibility for the project and better organization for Github as a whole.

**Comment by danielbuechele** [comment]
I created a project for the next minor version of Goofy. My idea is to select bugs and features to be addressed in the next release and track the progress of them there. I hope this provides a little more transparency for the development.
Also it would be great to find people to jump on the issues in the "selected for development" column and creating PRs for them.
