### ISSUE TITLE
Crash when opening link

### ISSUE THREAD

**Issue by rcheetah** [danielbuechele/goofy#314]
Everytime I open a link, the programm crashes. As simple as that.

OSX El Capitan (10.11.6)
iMac (Retina 5K, 27-inch, Late 2015)
Processor 3,2 GHz Intel Core i5
Graphic Card: AMD Radeon R9 M390 2048 MB

Goofy Version 2.2.6 (973)

**Comment by xxdavid** [comment]
Duplicate of #311. Please search the issues before creating a new one.

**Comment by rcheetah** [comment]
Sorry, my bad

**Comment by cadavre** [comment]
Close issue then.

**Comment by joallard** [comment]
Indeed, came here on a search, please close ;)
