### ISSUE TITLE
Custom CSS/Themes

### ISSUE THREAD

**Issue by duk242** [danielbuechele/goofy#316]
When v2 comes along, any chance of the ability to add in custom CSS or theming support?

Keep up the good work :D

**Comment by CoWinkKeyDinkInc** [comment]
I would love to see a dark theme for this, maybe better animation support too.

**Comment by danielbuechele** [comment]
I personally will not work on a dark theme, but PRs are welcome.

**Comment by duk242** [comment]
Sick. Count me in, when the new electron version goes live I'll start playing with the CSS files.

**Comment by duk242** [comment]
Update: Yep, with a modified CSS file it can be done and looks pretty sick.  This is just a work in progress. 
![goofydark](https://cloud.githubusercontent.com/assets/8278305/23449252/ad4bccd6-fea9-11e6-8c59-5cc14ca74047.png)

Is it possible to add in some sort of option to allow it to load a custom CSS file on top of the other CSS file that's in there?  I just tacked my CSS code to the bottom of fb.css (which isn't ideal as it involves either compiling it yourself or popping open the asar file and editing it manually).

**Comment by danielbuechele** [comment]
I think the best way is to compile the application yourself.

**Comment by sarnason** [comment]
I would vote for just supporting Dark Mode instead of going to full theme support.

**Comment by jklp** [comment]
@sarnason I've had a look and dark mode looks like it requires quite a significant amount of CSS / maintenance burden (as messenger.com is react, class names seem to change quite often).  

I was thinking if we could bundle Goofy with a default dark.css (downloaded from userstyles.org or something) but then let the user add their own / update the dark.css it might be a better solution.  

I personally don't use dark mode thought the thought of updating literally dozens of styles (nearly hundreds for some themes I've found) sounds like a maintenance nightmare.  

I'm happy to put in the theming though if someone who uses dark mode who would maintain the CSS that might be the idea setup?

**Comment by aldotroiano** [comment]
My objective will be to bring dark mode in Goofy. I'll keep you updated

**Comment by jklp** [comment]
Closing as seems that this issue was opened to address adding dark mode - which has been scheduled for release in v3.5.2 and addressed by #397
