### ISSUE TITLE
Crash on startup in version 2.2.7

### ISSUE THREAD

**Issue by hacker112** [danielbuechele/goofy#317]
Workaround was to go back to 2.2.6 that works find.
Attaching core dump.

[Goofy-2.2.7-Startup-Crash.txt](https://github.com/danielbuechele/goofy/files/782707/Goofy-2.2.7-Startup-Crash.txt)

**Comment by danielbuechele** [comment]
My first guess is that this is related to older versions of macOS

**Comment by hacker112** [comment]
Might be. 

Sadly I cannot upgrade, 10.11.6 is the newest that can be installed on this monster machine of a Mac Pro even though it would be fast enough.

**Comment by komanaki** [comment]
Hi there, I'm also having the issue on OS X 10.11.6, so it might be the cause yeah.

**Comment by tarikd** [comment]
Yes, I'm having this issue with the latest version of macOS

**Comment by danielbuechele** [comment]
I remove 2.2.7 for now. And will ship a 2.2.8 shortly.
