### ISSUE TITLE
Remember Window Size when Reopened (v3.0.0 Beta)

### ISSUE THREAD

**Issue by duk242** [danielbuechele/goofy#323]
When you quit and reopen the app, the window resets to the center of the screen and the default window size.

**Comment by danielbuechele** [comment]
There are a couple of problems with that discussed here: https://github.com/electron/electron/issues/526
But I agree that it should be added.

**Comment by MZhoume** [comment]
@danielbuechele This keeps bothering me. Hope its gonna be fix soon.

**Comment by jdahdah** [comment]
Sorry, I love Goofy, but this is a deal breaker for me. Downgraded to [2.2.6](https://github.com/danielbuechele/goofy/releases/tag/v2.2.6), which still works perfectly fine, until this is fixed.

**Comment by mrleblanc101** [comment]
If you can't remember the size, could you make the launch size bigger for now ? It's microscopic on my MacBook Pro 15"

**Comment by dregenor** [comment]
what about ubuntu?

**Comment by RvMouche** [comment]
@dregenor please open a new issue for seperate issues please.

**Comment by krvajal** [comment]
This is realted to #380
