### ISSUE TITLE
the sidebar has no padding

### ISSUE THREAD

**Issue by jonlee108** [danielbuechele/goofy#325]
The icons in the sidebar hug the very right side of the window and it looks bad.

See here: 
https://www.dropbox.com/scl/fi/9ac4dadt8aqodcc3s9lf8/screenshot%202017-03-01%2013.15.20.png

**Comment by danielbuechele** [comment]
This seems to be a Goofy v2 bug. I am not seeing this in v3. Let me know if this happens in v3, too.

**Comment by jonlee108** [comment]
huh where can i download v3?

**Comment by jonlee108** [comment]
aaah i didnt even realize i was a version behind.  just found it.

**Comment by danielbuechele** [comment]
There is still a problem with auto-update. This is why you might not get notified about the new version.
