### ISSUE TITLE
Make messenger options available

### ISSUE THREAD

**Issue by RvMouche** [danielbuechele/goofy#326]
Since 3.0.1 it's no longer possible to access the messenger.com settings. In goofy 2 you could access it through the menu bar and with `cmd ,`.

I assume you could trigger a javascript click event on the currently hidden element.

**Comment by danielbuechele** [comment]
Good idea. We should add that!

**Comment by TCB13** [comment]
Yep, this is annoying, someone forgot to port the menu bar option to the new App.

Keep up the good work ;)
