### ISSUE TITLE
Automatic update to 3.0.1 broken.

### ISSUE THREAD

**Issue by Etheryte** [danielbuechele/goofy#327]
Currently, trying to automatically update from 2.2.7 to 3.0.1 downloads the update and then gives the following error:

<img width="532" alt="screen shot 2017-03-02 at 01 06 40" src="https://cloud.githubusercontent.com/assets/3171718/23485566/a17d99c6-fee4-11e6-92d0-28d442b9b58a.png">

Looking at Goofy's activity in the Console, the following error is thrown numerous times:

`default	01:06:28.882786 +0200	Goofy	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG`

**Comment by danielbuechele** [comment]
Having that too, not sure where this comes from. The bundle identifier changed, perhaps that's the problem. I am currently building a version with the old bundle identifier.

**Comment by danielbuechele** [comment]
This is fixed now.
