### ISSUE TITLE
Battery Drain - Goofy makes Macbook Pro switch to discrete graphics

### ISSUE THREAD

**Issue by LanderN** [danielbuechele/goofy#328]
Using a 2016 Macbook Pro 15" with discrete graphics (Goofy 3.0.1.2).

Goofy makes the system switch to discrete graphics mode (gfxCardStatus notifies me when switching occurs). This creates a huge battery drain caused by Goofy.

System switches back to integrated graphics once Goofy quits.

**Comment by Vilscon** [comment]
Hm, if anyone finds out why this is happening, please write out extensively what's causing this. [Franz](http://meetfranz.com), the multi-social-App, is having this exact issue and only when using Messenger. It caused me to drop Franz and move to Goofy. I'm glad I'm reading this before updating Goofy from 2.2.x to 3.x.

Hopefully a solution to this problem will address the same issue that's causing it over at Franz.

**Comment by danielbuechele** [comment]
What @Vilscon describes sounds like Facebook is doing something that causes the graphics card switch. Perhaps it is somehow related to video elements used on the page? Does this happen in Chrome, too?

**Comment by Vilscon** [comment]
@danielbuechele Oh that's odd and might be pointing in the direction of the issue. I tested it right away and yes, directly when I launched Messenger in Chrome it fired my dedicated GPU, just like Goofy v3 and Franz do. Got no clue where to look next, though.

**Comment by danielbuechele** [comment]
I found this, what could fix the problem: https://github.com/electron/electron/blob/master/docs/api/app.md#appdisablehardwareacceleration

**Comment by Vilscon** [comment]
@danielbuechele Is there any chance I can try this for you with Chrome, by injecting some code or something? Would be great if I could use Goofy, or any other Facebook app/website, without the additional unnecessary battery usage.

**Comment by ialexryan** [comment]
Can confirm that launching Goofy 3.0.3 triggers the discrete GPU on my mid-2012 MBPr running macOS 10.12.3.

Meanwhile, launching messenger.com in Chrome 56 does _**not**_ trigger the discrete GPU.

So presumably it's not Facebook's fault, just some weird behavior in Electron.

**Comment by danielbuechele** [comment]
Since version 3 Goofy does not use messenger.com but facebook.com/messages.
Goofy 2 used WKWebKit instead of chromium so behaviour may be completely different.

**Comment by Vilscon** [comment]
In contrary to @ialexryan my GPU switches to the dGPU on both Facebook.com/messages and messenger.com. I don't, however, understand the use of Facebook.com/messages instead of Messenger.com, since the latter uses (as visually present) less elements, thus lower page weight? Oh well, I'm not developing it, so I assume you have your reasons? :)

Looking forward to the next version.

**Comment by jtbandes** [comment]
I noticed that running Goofy via `/Applications/Goofy.app/Contents/MacOS/Goofy --disable-gpu` (which I believe is equivalent to `app.disableHardwareAcceleration()`) fixes this problem.

However, there might be some legitimate cases for it to use the discrete GPU (playing videos?) where this would not help…

**Comment by beneisner** [comment]
Attempting @jtbandes  workaround does fix the discrete GPU issue, but totally breaks full-screen behavior (the window doesn't expand properly when moving to full screen/split screen).

**Comment by kerio92** [comment]
I launched goofy with `open /Applications/Goofy.app --args --disable-gpu` and my fullscreen works fine, including when i move in and out of split-screen fullscreen; window resizing is noticeably slow, however.

**Comment by danielbuechele** [comment]
Ok, so this is a trade-off we need to make. Either saving battery or having smooth animations. Currently, I can't think of a way to have both. Turning hardware acceleration on and off on the fly doesn't seem possible, because it is only possible before the mainWindow is rendered.

**Comment by jtbandes** [comment]
From a hardware standpoint it should be possible, although Electron/Chromium limitations might prevent you from doing it right now. Doesn't Safari (and maybe even Chrome) turn on and off the discrete GPU as needed?

**Comment by danielbuechele** [comment]
Yes, it should turn on and off hardware acceleration automatically. However, something on the page causes hardware acceleration to be always enabled.

**Comment by jtbandes** [comment]
Maybe some of this discussion will help to figure out which elements on the page are requiring the discrete GPU:
https://bugs.chromium.org/p/chromium/issues/detail?id=479299
https://bugs.chromium.org/p/chromium/issues/detail?id=158067
http://apple.stackexchange.com/a/171501/8318

**Comment by danielbuechele** [comment]
Hardware acceleration is disabled as of 3.1.0.

**Comment by LanderN** [comment]
<img width="683" alt="schermafbeelding 2017-03-13 om 15 16 03" src="https://cloud.githubusercontent.com/assets/12765267/23858222/013bc904-0800-11e7-8970-a7578b443e5f.png">
While Goofy doesn't use the discrete graphics anymore, it still has a considerable impact on battery life.
As you can see, Slack, another Electron app, has a much lower impact. (Both apps were in the background most of the time)

Goofy has 4-8 energy impact while hidden, Slack hovers between 0-2.
