### ISSUE TITLE
Doesn't support login approvals with messenger.com

### ISSUE THREAD

**Issue by peterjosling** [danielbuechele/goofy#33]
Just checked out the new changes to use messenger.com — I've got login approvals turned on on my account (and 2FA), so after entering my username and password it wants to kick me out to facebook.com to finish logging in.

![screen shot 2015-04-09 at 18 42 45](https://cloud.githubusercontent.com/assets/930324/7073008/639e9fa6-dee8-11e4-8adc-a4293dd47d06.png)

This kicks out to my default browser (Chrome), which of course doesn't share session data with Goofy's WebView, so I can't complete sign in. To get this working it'll need to handle loading Facebook within the app instead of kicking out to the browser.

**Comment by RvMouche** [comment]
As a workaround you can login into safari, keep safari open and try again -
worked to me. Also setting safari as default for a minute could change
this. [WKWebView shares data with Safari]

**Comment by peterjosling** [comment]
Ah, got it! I'd tried grabbing the link from Chrome and opening it in Safari, but it still wasn't letting me through. Relaunched it and it was already logged in.
