### ISSUE TITLE
Facebook menu bar appearing at top of Goofy window

### ISSUE THREAD

**Issue by aleminopuy** [danielbuechele/goofy#330]
Just updated to 3.0.3 and the top of the window now has the facebook blue top bar across the top. This may be planned and could be neat, however the close/minimize/maximize buttons are on top of the search bar.

<img width="835" alt="screen shot 2017-03-02 at 9 26 03 am" src="https://cloud.githubusercontent.com/assets/18608490/23513936/5daa95e0-ff2b-11e6-820b-2470aebbe847.png">

**Comment by danielbuechele** [comment]
This should not happen. Does anyone else have this issue? 
This is where the bar is hidden: https://github.com/danielbuechele/goofy-core/blob/388a40c877c5eac6db9759aabe1f1aab024c4843/src/assets/fb.css#L15-L17

Can you open facebook.com/messages in Chrome and see if the bar has that particular ID?

**Comment by RvMouche** [comment]
I'd go back to using messenger.com instead of facebook.com/messages, especially as facebook.com/messages and {workspace}.facebook.com/chat aren't necessary equal anyways. May fix #331 too.

**Comment by aleminopuy** [comment]
Looks like the id is  #fb2k_pagelet_bluebar, #blueBarDOMInspector,  or #u_0_3

Not sure if I'm looking up the right thing or doing it the right way, so I attached a screenshot. (used inspector in chrome)

![screen shot 2017-03-02 at 12 09 04 pm](https://cloud.githubusercontent.com/assets/18608490/23520571/3746a63a-ff41-11e6-898e-a7ec9dfa9037.png)

**Comment by danielbuechele** [comment]
Ok. Looks good. I will hide this in the next update, too.
