### ISSUE TITLE
Goofy fail to open because it load before connecting to wifi 

### ISSUE THREAD

**Issue by mrleblanc101** [danielbuechele/goofy#338]
Hi,
I have set Goofy to launch on startup but unfortunately it load before the wifi connexion is made and throw a JavaScrip error.
![c6ajmeywmainklg](https://cloud.githubusercontent.com/assets/17392251/23591245/64cfcdd0-01bb-11e7-8239-e4859632e11a.png)

**Comment by royteeuwen** [comment]
Hey, 

I have the same issue! any update on this? Any workaround for this?

Greets
Roy

**Comment by jklp** [comment]
Closing for now as can't repro and have since updated to Electron v4 in v3.4.0. Lets re-open in future if it happens again
