### ISSUE TITLE
Smaller/bigger text

### ISSUE THREAD

**Issue by RvMouche** [danielbuechele/goofy#34]
Would be nice if I could change the size of the text with cmd - / cmd + like in safari, but a bit more gradual so I can make it the same size as my iMessages, having both windows next to each other (I use a space for texting) looks weird now.

**Comment by sposterkil** [comment]
:+1: Low priority, but would be nice.

**Comment by mrbax** [comment]
Hard to read on a high-resolution screen.  Really need to be able to scale text.

**Comment by ZacCranko** [comment]
Bump

**Comment by bmedici** [comment]
Would be really nice to be able to have a smaller font, tu save screen real estate :)
