### ISSUE TITLE
Goofy Helper requries discrete graphics

### ISSUE THREAD

**Issue by wizonesolutions** [danielbuechele/goofy#342]
Usually after Goofy has been open for a bit, gfxCardStatus 2.4.3i tells me that a process called Goofy Helper is using discrete graphics. (The same sometimes happens with Slack.)

Any idea what that process is? Maybe it's an Electron thing.

Running latest Goofy.

**Comment by danielbuechele** [comment]
This should be fixed in version 3.1.0
Let me know it this still happens.
