### ISSUE TITLE
Conversation option display problem

### ISSUE THREAD

**Issue by mrleblanc101** [danielbuechele/goofy#346]
Hi, When I click the "i" icon in the top right, then the gear icon to access the conversation option, the options appear out of the application windows (see screenshot). Related #343 
![img 2017-03-14 a 22 01 17](https://cloud.githubusercontent.com/assets/17392251/23930323/0d256204-0902-11e7-9116-5f29338db374.png)

**Comment by leocaseiro** [comment]
I confirm this issue.

**Comment by leocaseiro** [comment]
Thanks for the fix! it's working great now!
