### ISSUE TITLE
Can't open preferences

### ISSUE THREAD

**Issue by MekliCZ** [danielbuechele/goofy#348]
When I click to Preferences in menu bar or I press CMD+, nothing happens. If there are no preferences, it would be nice to remove it from menu bar.

**Comment by leocaseiro** [comment]
I can't reproduce that. I'm on mac os and if I click at preferences I can see the settings:

<img width="544" alt="screen shot 2017-04-04 at 10 04 04 pm" src="https://cloud.githubusercontent.com/assets/940070/24655713/adbbcf38-1982-11e7-9ba6-541b6026c6dc.png">

**Comment by leymannx** [comment]
Confirming issue on freshly installed macOS Sierra.

**Comment by gslender** [comment]
me too... no preferences open... any log file or how to see error messages so I can report something else? btw also on fresh sierra

**Comment by gslender** [comment]
I closed the app and re-opened and now it does show preferences... so maybe this is a one time thing??

**Comment by danielbuechele** [comment]
Which version of Gooy are you on? 3.2.1 is the latest.

**Comment by prosello** [comment]
Upgrading from 3.2.0 to 3.2.1 fixed this issue for me.

**Comment by MekliCZ** [comment]
I have updated to 3.2.1 and I still can't open preferences, so there isn't any change that fixes the issue in 3.2.1.

**Comment by leymannx** [comment]
@MekliCZ Does completely closing and reopening fix the issue?

**Comment by AwaitingIrindul** [comment]
The issue is still valid for version 3.2.2 on macOS High Sierra (10.13.2). 
I tried closing and reopening the app without success. I even rebooted but still no preferences.

**Comment by jklp** [comment]
Created a pull request at #427 which should fix this

**Comment by jklp** [comment]
Fixed in v3.3.2
