### ISSUE TITLE
Activating window does not mark message as read

### ISSUE THREAD

**Issue by gklka** [danielbuechele/goofy#353]
Activating Goofy's window does not clear the current conversations message status from unread, I had to directly click into the text input field to do so. I don't know this is a Goofy feature or a messenger.com one, but if possible I'd be happy to see it changed.

**Comment by jklp** [comment]
Hi, have confirmed and this no longer seems to be the case (was potentially a messenger.com bug?)

Can you please re-open and we can re-evaluate putting it in
