### ISSUE TITLE
Unable to Load when facebook.com is null-routed

### ISSUE THREAD

**Issue by marchuot** [danielbuechele/goofy#354]
Before v3.0, Goofy would work fine if facebook.com was unreachable but messenger.com was reachable. This edge case is useful if you wanted to add an entry in your hosts file to block facebook.com (eg: the timeline product) but still access the messenger product. A new dependency in v3 that requires facebook.com to be reachable for the Goofy interface to load at all. Is this something that could be worked around?

**Comment by Etheryte** [comment]
Currently, the app uses `https://www.facebook.com/messages` as the source URL, not `https://www.messenger.com`. I would assume this to be a conscious decision by the developer, but I'm not aware of the rationale.

**Comment by danielbuechele** [comment]
discussion in #360
