### ISSUE TITLE
Cannot create browser window before app is ready

### ISSUE THREAD

**Issue by mrleblanc101** [danielbuechele/goofy#357]
<img width="504" alt="img 2017-03-22 a 15 18 57" src="https://cloud.githubusercontent.com/assets/17392251/24304611/42c7a1be-10ba-11e7-856b-17b5c0063a1e.png">
I get this error every now and then, but cannot reproduce it.

**Comment by jklp** [comment]
Closing for now as can't repro and have since updated to Electron v4 in v3.4.0.  Lets re-open in future if it happens again
