### ISSUE TITLE
Discussion: code organization

### ISSUE THREAD

**Issue by Etheryte** [danielbuechele/goofy#359]
While the discussion mostly applies to [goofy core](https://github.com/danielbuechele/goofy-core), I made the issue here, since all issues are tracked under this repository at the moment.

Currently, the code structure is rather involved in certain places and would it would probably be both easier to maintain and merge pull requests if functionality was divided into modules. Some work has already been done on that front with the [menu component](https://github.com/danielbuechele/goofy-core/blob/master/src/menu.js), but I think in the long term, the whole codebase could benefit from granularity.

Would pull requests be welcome on this regard?

**Comment by danielbuechele** [comment]
First of all, thank you so much for your support. Sorry, I didn't have much time lately to maintain Goofy and merge your PRs.

But regarding your point, yes, creating these modules, seem like a really good idea! So feel free to create PRs.
I still haven't had a good idea to manage goofy core and the two separate projects. Perhaps I would make more sense to put goofy into this project and reference it from Goofy for Work. What do you think about this?

**Comment by Etheryte** [comment]
At the time, it's somewhat unclear to me why Goofy and Goofy for Work need to be in separate projects. Both of the repos hold almost entirely metadata and assets while the main code is in the core repository. Wouldn't it be possible to keep them together and simply make the Goofy/Goofy for Work distinction a part of a build step?

**Comment by jklp** [comment]
Closing as Goofy for Work support has been removed (for now - see #430).

Have also started splitting out components in v3.4.1 to make managing menus / touch bar modules easier (is this what was meant?)
