### ISSUE TITLE
New icon for notifcations

### ISSUE THREAD

**Issue by RvMouche** [danielbuechele/goofy#36]
Think the old icon is still somewhere in the resources
![screen shot 2015-04-09 at 20 25 22](https://cloud.githubusercontent.com/assets/2125224/7074871/0b90eb32-defe-11e4-839a-f546cd4523af.png)

**Comment by danielbuechele** [comment]
Is this happening to anyone else? I think is comes from some local caching of the icon?

**Comment by danielbuechele** [comment]
I consider this as obsolete
