### ISSUE TITLE
Using Goofy with a deactivated Facebook account

### ISSUE THREAD

**Issue by pieterdd** [danielbuechele/goofy#360]
I deactivated my Facebook account, but opted to keep my Messenger account. I noticed that when starting Goofy, I see the Facebook login and not the Messenger login. Is it possible that Goofy reactivates my Facebook account when logging in?

**Comment by Etheryte** [comment]
Goofy uses `https://www.facebook.com/messages` as the gateway internally so you can easily test it: if there are no complications when using it through there in a browser, you should be good to go.

**Comment by pieterdd** [comment]
Dang, it doesn't look like I can log in there without reactivating my account. Any specific reason why the app doesn't use https://www.messenger.com/login?

**Comment by Etheryte** [comment]
I'm not sure why that route is used at the moment, it may be something to do with easier integration with the Facebook for Work chat, but it's hard to tell unless @danielbuechele chimes in himself. See https://github.com/danielbuechele/goofy/issues/354 for a related discussion.

**Comment by danielbuechele** [comment]
The Facebook route is used, because that way Goofy and Goofy for Work can use the same code.
I think not having a Facebook account, but using Messenger is a real edge-case. And if there are no other reasons, I would stick to facebook.com instead of messenger.com

**Comment by c17r** [comment]
Yeah, I just deactivated my FB but left messenger.  www.messenger.com works fine but Goofy is no longer an option.  Sad.

**Comment by jklp** [comment]
As in #375, have now switched to use messenger.com
