### ISSUE TITLE
Window caption in Mission Control says "Goofy at Work"

### ISSUE THREAD

**Issue by PierreMesure** [danielbuechele/goofy#361]
I'm using the normal version of Goofy so I guess it's a bug. Quite easy to correct, though.

![capture d ecran 2017-04-01 a 22 26 59](https://cloud.githubusercontent.com/assets/7223028/24582225/429ee8b0-172b-11e7-8100-3770d79547b3.jpg)

**Comment by Etheryte** [comment]
I've made [a pull request](https://github.com/danielbuechele/goofy-core/pull/3) to resolve this issue.
