### ISSUE TITLE
Reaction buttons can go past the edge of the window

### ISSUE THREAD

**Issue by jtbandes** [danielbuechele/goofy#362]
Clicking on the <img src="https://cloud.githubusercontent.com/assets/14237/24593040/fd576e72-17d3-11e7-9a57-c121e9058b08.png" width="40"> icon next to a message now brings up reaction controls:

<img width="302" alt="screen shot 2017-04-02 at 6 41 44 pm" src="https://cloud.githubusercontent.com/assets/14237/24593052/29c5904c-17d4-11e7-87e2-9f41cc8f6e9f.png">

However if the message is large enough, they can go past the edge of the window:

<img width="127" alt="screen shot 2017-04-02 at 6 42 29 pm" src="https://cloud.githubusercontent.com/assets/14237/24593049/255297f8-17d4-11e7-81c0-4c351005ed98.png">

This makes it impossible to click on some of the buttons. It would be nice to reposition them so they're onscreen.

**Comment by jtbandes** [comment]
If it helps, the <img src="https://cloud.githubusercontent.com/assets/14237/24593040/fd576e72-17d3-11e7-9a57-c121e9058b08.png" width="30"> button is `<span class="_5zvq"><i class="img sp_gsUMgDKXpnY sx_e463ce">...`, and the reactions themselves are `<span class="_1z8r"><span><img alt="😍" class="_1ift _5m3a img" ...`.

**Comment by Etheryte** [comment]
This issue actually also occurs on the regular messenger page, so it's very likely it will be fixed by Facebook at some point in time.
