### ISSUE TITLE
Chat settings is too wide and I can't read. (CSS bug)

### ISSUE THREAD

**Issue by leocaseiro** [danielbuechele/goofy#363]
I'm on mac os and if I open the chat and click in settings, I can't see anything:

![goofy-bug-settings](https://cloud.githubusercontent.com/assets/940070/24656363/91302bf4-1985-11e7-8e73-00baf76d1c29.png)

**Comment by Etheryte** [comment]
Duplicate of https://github.com/danielbuechele/goofy/issues/346.

**Comment by leocaseiro** [comment]
Sorry @Etheryte, I try to search as "settings" and I couldn't find.

Closing this issue, so we keep the old one.
