### ISSUE TITLE
The whole window is glitching

### ISSUE THREAD

**Issue by KTamas** [danielbuechele/goofy#364]
I know this is hard to reproduce and even hard to report but for the last, I don't know, 2-3 weeks or so, Goofy's window had been randomly glitching. The entire window. 

(I don't think it's something with my computer as it's only Goofy doing it)

**Comment by Etheryte** [comment]
Could you try explaining what "glitching" means? As it is, it's nigh impossible to understand what you mean.

**Comment by KTamas** [comment]
Right. I'll try.

First of all on closer observation it doesn't happen to the contact list, only the rest of the window.

Second... here's a screenshot of something completely different that illustrates what I mean by glitching: http://i.imgur.com/26qGQwr.jpg

That's all I can say. I know, not a lot to go on.

**Comment by andremiguelaa** [comment]
The same thing happens to me frequently :(

**Comment by jklp** [comment]
Yikes ... could be a problem with Electron?  I've upgraded Electron to 2.0.x recently (since v3.3.3) - if you could reopen the issue if you still experience it and we can look into it.
