### ISSUE TITLE
Suggestion: Touchbar "New conversation" (CMD+N)

### ISSUE THREAD

**Issue by Vilscon** [danielbuechele/goofy#372]
Simple suggestion, instead of showing all latest chats.. a simple button (chat icon with a +) to start a new conversation. Would be a nice addition to the minimal current touchbar functionality of Goofy.

**Comment by jklp** [comment]
Agreed, list of latest chats is a pretty bad use case for the touch bar (no other messaging / email / etc app does this) 

Added in v3.3.5 issue #335.
