### ISSUE TITLE
Let us choose between messenger.com or fb.com/messages

### ISSUE THREAD

**Issue by mrleblanc101** [danielbuechele/goofy#375]
I'm not sure if this would be too complicated because of your custom JavaScript and CSS but it would be an interesting option.

**Comment by Vilscon** [comment]
Just wondering out of personal interest.. what would be the difference? Just opened both sites and, except the blue Facebook top nav bar, I saw no differences.

**Comment by pawelantczak** [comment]
Hi.
If you have Messenger account without FB account, you can't login via fb.com, only messenger.com.

**Comment by jklp** [comment]
That's not a bad point!  Ok I'll aim to get it done!

**Comment by Vilscon** [comment]
Just got to add in on this discussion again, as I'm receiving notifications..

So the looks and functionality of fb.com/messages and messenger seem exactly the same and..
if you have a FB account, you can log in on Messenger and fb.com/messages, while if you only have a messenger account, you can only log onto Messenger.com. There is no scenario when one can only log onto fb.com/messages. So in either scenario, you'll always succeed with messenger.com

Then why would you want fb.com/messages?

**Comment by jklp** [comment]
As mentioned good points all round.  Have just released 3.4.0 which uses messenger.com by default.
