### ISSUE TITLE
JavaScript exception error when waking MacBook from sleep

### ISSUE THREAD

**Issue by mrleblanc101** [danielbuechele/goofy#376]
<img width="532" alt="img 2017-04-25 a 23 21 14" src="https://cloud.githubusercontent.com/assets/17392251/25408449/4ed0796e-2a0e-11e7-8589-3e7740a1adb6.png">

**Comment by Etheryte** [comment]
Duplicate of https://github.com/danielbuechele/goofy/issues/373.  
For future reference, it's better to share the error in text form, it's not possible to search for the error message when it's in an image.

**Comment by jklp** [comment]
Close as duplicate of #373
