### ISSUE TITLE
Audio clips won't finish sending if you click to another user 

### ISSUE THREAD

**Issue by mayeaux** [danielbuechele/goofy#379]
If I record an audio clip, and then click to another user before it's finished sending, the audio clip never sends it just stays with it's in progress spinner indefinitely.

Ugh, has happened to me so many times, would love to see this fixed my audio clips are dropping like flies :( 

(Still love the software though & thanks a lot for the app)

**Comment by jklp** [comment]
Might have been a bug with messenger.com as just tried and can't seem to replicate

If it still occurs let me know and I'll reopen
