### ISSUE TITLE
Sticker Search Gone

### ISSUE THREAD

**Issue by thomaswrenn** [danielbuechele/goofy#38]
The Sticker search field is missing now! And there's no way to get to it.

![screenshot 2015-04-09 19 16 06](https://cloud.githubusercontent.com/assets/1128624/7080806/e7fc1932-deec-11e4-9898-7b9ee00246a3.png)

Loved being able to hit the sticker button and start typing to search stickers immediately. (Search field is still there on messenger.com and works as described.)

**Comment by danielbuechele** [comment]
Facebook seems to run AB-tests here. I don't have the search at all. Not in Goofy, not in Safari or Chrome.

**Comment by thomaswrenn** [comment]
Aw man, those bastards. It's awesome, Facebook, roll it out to everyone! Thanks. 
![napkin 04-10-15 10 30 40](https://cloud.githubusercontent.com/assets/1128624/7093287/a78cf42c-df6c-11e4-9894-e6fa65876a12.png)

My solution right now is to have both Chat.app and Goofy installed so I can respond with a search sticker fast xp. Weird that it's consistently different for me (the same user) in these two apps. And weird that the window isn't shorter to get rid of the negative space on the bottom under the categories.

**Comment by thomaswrenn** [comment]
Yay, it's working now. 

Not sure if from an update from you or if because I deleted some sticker sets on my phone and that reset something that was causing a bug in Goofy. 

Will let you know if the search disappears again.
