### ISSUE TITLE
No longer shows up

### ISSUE THREAD

**Issue by rwwagner90** [danielbuechele/goofy#383]
I assume there is some sort of error happening, but when I launch Goofy, it never shows up. It does "open" as the name shows up in the menu bar, and a dot it under the icon, but I never get the actual app to show up. It used to work, and recently broke, a couple weeks ago.

**Comment by jklp** [comment]
Can't replicate in v3.3.3.  Can you download the latest version and try again?  If it's still blank, could you delete `~/Library/Application Support/goofy*` and try opening again.  

If it still occurs, please reopen the ticket and we can look into it.
