### ISSUE TITLE
Reloading issues with Goofy after Mac wakes from sleep

### ISSUE THREAD

**Issue by nuno-agostinho** [danielbuechele/goofy#385]
Many times after waking my Mac from sleep, Goofy does not reload the interface and seems to be working as expected, even if there are new messages. However, after performing a manual reload (i.e. View > Reload), Goofy will show those messages fine.

The easy solution seems to be to automatically reload Goofy when a Mac wakes from sleep, although I have no idea if macOS returns such information.

**Comment by jklp** [comment]
Can't seem to replicate in v3.3.3 - please reopen if still experiencing and can investigate.

**Comment by shaunc869** [comment]
I have this same issue, when waking from sleep the chat doesn't update from previous messages in a group chat and needs to be restarted to work.
