### ISSUE TITLE
I think Goofy just posted to my wall?

### ISSUE THREAD

**Issue by broketheinterweb** [danielbuechele/goofy#386]
I sent a friend a link via Goofy, and later noticed it was posted to my wall with no context as a public post... timestamped from when I sent it through the messenger.

I didn't have facebook open in-browser at the time, and this was on an older release (the in-app update prompt has not been working for me so I'm on a slightly older version. 3.0.3)

I can't be 100% sure Goofy caused this, but it's the only place I sent this link and it's definitely not a link I wanted to share with Facebook friends. Fortunately Facebook automatically removed it, thinking it was a spam link anyway.

**Comment by ashthunt** [comment]
Well, this is nightmare fuel. I'm going to investigate out of pure self-preservation.

**Comment by danielbuechele** [comment]
can not reproduce
