### ISSUE TITLE
Enable Substitutions menu

### ISSUE THREAD

**Issue by gklka** [danielbuechele/goofy#387]
macOS standard Edit menu contains a "Substitutions" menu item, which shows toggles for enabling or disabling Text replacement and other things. Please enable this menu item in Goofy.

Goofy:
<img width="239" alt="screen shot 2017-08-16 at 11 10 28" src="https://user-images.githubusercontent.com/866694/29356169-b04a7470-8273-11e7-8dac-48788e26d72f.png">

Safari:
<img width="455" alt="screen shot 2017-08-16 at 11 10 47" src="https://user-images.githubusercontent.com/866694/29356177-b706b24c-8273-11e7-9616-f5e876a89638.png">

**Comment by jklp** [comment]
Closing as duplicate of #333
