### ISSUE TITLE
Enable Spellcheck

### ISSUE THREAD

**Issue by chikkevin** [danielbuechele/goofy#388]
On the latest build of Goofy 3.2.2 (2001), users are not able to use spell check as users are able to write incorrect words. Please add spell check to your next update.

**Comment by thatchrismiller** [comment]
I agree. This would be awesome. (Using the Mac version.)

**Comment by scf4** [comment]
I agree 😄

**Comment by thatchrismiller** [comment]
Any hopes of this being fixed/updated?

**Comment by Mattiaslndstrm** [comment]
Yes, please! I really miss this feature.

**Comment by alexkatz** [comment]
This would be great.

**Comment by jklp** [comment]
Fixed in v3.4.1
