### ISSUE TITLE
Growl Notification when I Send Message

### ISSUE THREAD

**Issue by JSchaenzle** [danielbuechele/goofy#389]
Whenever I send a message to someone, I see a growl notification that shows the message that I just typed.  I think this just started happening in the last month or so. Anyone know why this is happening?

**Comment by scf4** [comment]
Same here!

**Comment by Vilscon** [comment]
Just wondering, but why are you using Growl, instead of the native notification service of macOS, assuming you aren't using Windows of course. That would explain itself already..

**Comment by scf4** [comment]
Perhaps he was mistaken in calling it a growl notification. I have this issue with the default notification system.

**Comment by MustafaHaddara** [comment]
I have the same issue with the default notification system.

**Comment by samuel-finistere** [comment]
same !

**Comment by LucasAdam** [comment]
Same issue

**Comment by scottbarrow** [comment]
+1, annoying. I've tried toggling desktop notifications but they still appear

**Comment by lkostrowski** [comment]
+1, only solution is to disable all notifications for an app

**Comment by Serneum** [comment]
+1. I've been seeing this for a while and have just ignored it for the most part. I was hoping for an update that would fix it but haven't seen one come through

**Comment by danielbuechele** [comment]
fixed in v.3.3.0
