### ISSUE TITLE
Is Goofy still in active development?

### ISSUE THREAD

**Issue by Vilscon** [danielbuechele/goofy#390]
Hey guys,

I'm still on Goofy V2.x, since at the last moment I checked (half year ago..) Goofy V3 was still using the external GPU, which caused additional battery drain. I assume this problem is solved, as hardware acceleration was removed in 3.1.0. 

However, the last update (3.2.2) was issued months ago and I want to make sure Goofy is still in active development. I don't want a Franz-situation, where half a bilion people used the service and suddenly all development stopped..

:)

**Comment by Vilscon** [comment]
Update:

Goofy, as of V3, still sucks. Like I wrote, I had Goofy V2 running all the time pre-High Sierra and I just started using Goofy V3.2.x. Well, I can simply say it 'sucks', i.e. lacking.

- There is Touch Bar support, but clicking any of the contacts doesn't change the window
- You get notifications (at least, some people do..), but in contrast to V2, you can't click them to reply via the notification

Want me to continue?

Glad at least the GPU bug is resolved..

**Comment by danielbuechele** [comment]
Hey,
yes, I am currently not able to continue the development of Goofy. If there are any people that want to take over, please let me know. But also small contributions can help to make Goofy better. One of the problems is, that there are a lot of different experiments run on messenger.com and so the app looks different for different people.
There is [Caprine](https://github.com/sindresorhus/caprine) which has the same idea, but seems to offer more features. Perhaps it would make sense to merge these projects.

Thanks,
Daniel

**Comment by Vilscon** [comment]
Hey Daniel,

Please don't interpret my previous comments as bad critics, but just informative. Too bad there is no development, but please know I enjoyed Goofy for the time being. Caprine offers some nice functionality, so I'll have it checked out. Else I might return to a previous version of Goofy if I can find it.

I'm a designer, not a Mac developer, so I can't contribute. But take care, Daniel!

**Comment by danielbuechele** [comment]
Due to many requests I fixed some bugs today. I can still not actively maintain Goofy but let's see if some PRs are coming up.
