### ISSUE TITLE
High resource usage

### ISSUE THREAD

**Issue by root0x** [danielbuechele/goofy#394]
For the last couple of days now goofy has been using 60-80% cpu. Which is an issue for my battery on my macbook pro

**Comment by scf4** [comment]
Yeah you need to kill it every few hours or so. It destroys my battery so I'm back to using the messenger.com website for now...

**Comment by jklp** [comment]
Can't replicate though since this issue was logged, Goofy has moved from a Swift app to an Electron app so systemic things might have changed which prevent this.

Closing for now but feel free to open and we can investigate further.
