### ISSUE TITLE
Cannot restore after reboot

### ISSUE THREAD

**Issue by gklka** [danielbuechele/goofy#395]
When you have relaunch running applications on and reboot your system with Goofy, after the reboot it can't resume with this error:

```
Uncaught Exception:
TypeError: Cannot read property 'getPrimaryDisplay' of null
    at App.createWindow (/Applications/Goofy.app/Contents/Resources/app.asar/src/main.js:80:33)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

**Comment by StyxOfDynamite** [comment]
+1 Also happens when upgrading from Sierra to High Sierra, probably the exact same issue but might see a few more people noticing it since they've pushed the update.

**Comment by jklp** [comment]
As we're now using `electron-window-state` we no longer encounter `getPrimaryDisplay()` so consequently this message is gone.
