### ISSUE TITLE
Could not display composer.

### ISSUE THREAD

**Issue by jonasborggren** [danielbuechele/goofy#396]
The bottom of a conversation (where you write text or add other media) sometimes turns into a text that says `Could not display composer.`.

Like this:
![Could not display composer.](https://i.imgur.com/ogSIYJn.png)

I have no idea why this happens. Hard to say even when this has happened to me. 
This has probably happened once every 2 hours. It usually fixes itself (IIRC) after a while so sometimes you don't even notice it.

I've had it for 5 minutes now. I'll update if this changes by itself.

I can imagine this not even being Goofy's fault and there might not even be anything to do about it.

Edit: This also applies for **all** conversations. So switching conversation doesn't help.
Edit2: All right, I had to use my chat so I had to restart the app. That fixed it.
Edit3: Happened again, just a few minutes later.

**Comment by gms8994** [comment]
I've had this happen when I've clicked on an image to zoom it, and then started typing before I've unzoomed the image. It doesn't happen if I've started typing before zooming the image; only when the text entry box is empty (this includes typing a message and deleting all of it).

**Comment by jklp** [comment]
I've been trying to repro but no go - assuming was a Messenger bug 🤷‍♂️ 

Due to the age of the issue I'm going to close for now but please reopen if it happens again.
