### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Sosoyan** [danielbuechele/goofy#397]
It's a feature request to have a  dark mode

**Comment by Cruplezone** [comment]
Pretty sure Daniel said at one point he is not actively working on adding anymore features. Caprine has this feature, plus some other colour modes.

**Comment by danielbuechele** [comment]
I will not develop this feature. If somebody wants to any PR is welcome

**Comment by sarnason** [comment]
I did a test implementation. Seems as for now there isn't support for the embedded WebView for the new CSS media query for "prefers-color-scheme". Once this is in place I can implement automatic dark mode easily. Let's wait for a few weeks.

**Comment by sarnason** [comment]
Apple will add this support in an OS update in the coming months. It's already working in the latest Safari Tech Preview.

**Comment by jklp** [comment]
@sarnason Lol we jumping around tickets today

From what I understand prefers-color-scheme only detects if the user has selected dark mode in macOS - but doesn’t actually update the CSS to dark mode (needs to be supported by messenger.com itself) 

If you have the CSS already, I have an idea of how to implement it (just add a “dark” class to the root <body> or something and toggle via settings)

**Comment by sarnason** [comment]
Hi @jklp. Yes some issues to deal with indeed.
(FYI, I am an ex Apple OS eng.) there is a Media Query that gets dynamically updated once the user changes the UI theme in System Preferences. Now it seems that the current framework is based on an older version of WebKit not including the required support detecting the "prefers-color-scheme". The reason I am proposing us to relax for a while has to do with the fact that eventually we will get all we need soon. Basically one will be able to add "@media only screen and (prefers-color-scheme: dark) {.." to the fb.css and get all the overrides required soon enough.

**Comment by sarnason** [comment]
Just for fun I have this version running on my local OS looking just great.

**Comment by jklp** [comment]
Ah makes sense, happy to sit tight for Apple.  If you want to send me some screens / chat about impl can DM me on twitter :)

**Comment by CFarzaneh** [comment]
Hey for anyone still interested in this, I made a fork and added Dark Mode that can be enabled from the File menu. It works by loading a .css file. There's still work that needs to be done before a PR. I'd like to add auto enable and maybe detect if macOS dark mode is enabled, and improve the CSS. But it works for now so feel free to try it out :)

**Comment by jklp** [comment]
@CFarzaneh Hey dude I checked out your repo - can you DM me on twitter as I think you're pretty close!  (I'm @jklp on twitter)

**Comment by jklp** [comment]
@CFarzaneh Oh sorry - I just implemented using the theme from https://github.com/auscompgeek/fb-messenger-dark (seems to be updated quite often and is one of the better ones), and added an option in the preference plain to turn on.

Will be in the upcoming v3.5.2 release
