### ISSUE TITLE
Broken TouchBar icons after app 'reload'

### ISSUE THREAD

**Issue by petr-ujezdsky** [danielbuechele/goofy#408]
1. Open Goofy
2. TouchBar shows most recent conversations
3. Clicking those buttons switches the conversations properly
4. Hit <cmd> + R (or View -> Reload)
5. TouchBar conversations stay same, but clicking them does nothing from now on

I suspect that during the Reload the conversation references are lost and buttons then broke.

**Comment by jklp** [comment]
Changed the way the touchbar works now - instead of using to swap between conversations, can now perform actions on the conversation e.g. mute, archive, etc.  

This was completed in v3.3.5
