### ISSUE TITLE
Settings Icon is under the Exit/Minimize/Maximize UI buttons in the top left

### ISSUE THREAD

**Issue by theforevermachine** [danielbuechele/goofy#409]
Can't open settings, the gear icon is stuffed underneath the window controls in the top left of the app window
![issue](https://user-images.githubusercontent.com/37224656/37224959-082841f6-23a3-11e8-843a-ce5564709cb6.jpg)

**Comment by killbom** [comment]
https://github.com/danielbuechele/goofy/pull/411

**Comment by jklp** [comment]
Created a pull request at #427 which should fix this

**Comment by jklp** [comment]
Fixed in v3.3.2
