### ISSUE TITLE
Settings button over the osx buttons

### ISSUE THREAD

**Issue by pintiliedragosgeorge** [danielbuechele/goofy#410]
the settings button of the site is over the 3 buttons of the windows
![screen shot 2018-03-12 at 15 05 48](https://user-images.githubusercontent.com/37209878/37285203-f62ae6c8-2606-11e8-84f1-0479df14e22e.png)

**Comment by petr-ujezdsky** [comment]
Duplicate to #409

**Comment by killbom** [comment]
https://github.com/danielbuechele/goofy/pull/411

**Comment by jklp** [comment]
Created a pull request at #427 which should fix this
