### ISSUE TITLE
“Hide Others” shortcut

### ISSUE THREAD

**Issue by ron-wolf** [danielbuechele/goofy#413]
In OS X system apps as well as most third-party apps, the shortcut to hide other apps is <kbd>Option</kbd> + <kbd>Command</kbd> + <kbd>H</kbd>, but in Goofy it’s <kbd>Shift</kbd> + <kbd>Command</kbd> + <kbd>H</kbd>. This is unexpected behavior.

**Comment by jklp** [comment]
Fixed in v3.3.3
