### ISSUE TITLE
Deeplinking

### ISSUE THREAD

**Issue by dustinblackman** [danielbuechele/goofy#417]
## Overview

Deeplinking like how [Slack](https://api.slack.com/docs/deep-linking) currently does it in to Goofy would be pretty awesome. It would open the door to making things like Alfred workflows for opening conversations really nice, similar to [slack-alfred](https://github.com/yannickglt/alfred-slack).

There seems to be an [decent example](https://github.com/oikonomopo/electron-deep-linking-mac-win) for Electron that can assist with this.

**Comment by jklp** [comment]
Related to PR #429 though I accidentally refactored and messed up your PR - have manually edited your PR so should be in v3.4.1
