### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by nezriffic** [danielbuechele/goofy#418]
Unable to use the app:
- App starts, but goes white after displaying logo.
- It started to bahave this way week ago? like after Safari 12.0 and Chrome 69 - where they (at least Safari) changed plugins policy (not sure it is related).
- Installing from scratch does not help.
- Dev console does not show anything.
- If logged out, app opens FB window to login - after successful login, it goes white.
- Messages indicator works (shows number on the icon correctly).

OS: 10.13.3
Goofy: 3.3.1

**Comment by nezriffic** [comment]
Unfortunately it does not, I already tried it.

**Comment by ken551113** [comment]
I use appClean to completely remove goofy then reinstall.It works for me.

**Comment by nezriffic** [comment]
what's appClean?

**Comment by ken551113** [comment]
http://freemacsoft.net/appcleaner/

**Comment by nezriffic** [comment]
it worked with it, thank you
