### ISSUE TITLE
Not working on Mojave

### ISSUE THREAD

**Issue by thunder87** [danielbuechele/goofy#419]
Not working on macos mojave, version 3.3.1

[Screenshot](https://image.ibb.co/jAzx9K/Sk_rmbillede_2018_10_01_kl_11_43_22.png)

**Comment by detrio** [comment]
Confirmed - just a blank screen.

**Comment by alextoub** [comment]
+1

**Comment by vogroupau** [comment]
Not working here either!

**Comment by digitalhank** [comment]
Not working on High Sierra either. I believe it stopped working last week after the big Facebook breach.

**Comment by alvinnguyen** [comment]
Hm strange, it's still working for me on 10.14

**Comment by digitalhank** [comment]
I think i figured out the issue: If you were logged in during the Facebook breach and was forcefully kicked out the app will display like @thunder87 screenshot. If you log out by clicking `File -> Logout` in the toolbar on the top left it will work again.

**Comment by vogroupau** [comment]
Worked perfectly thank you!


Kind regards

VO Support
[https://vogroup.com.au/assets/websiteunderline.png]
        [https://vogroup.com.au/assets/voEmailLogo.png]                 E
AU
NZ
        support@vogroup.com.au<mailto:support@vogroup.com.au>
1300 220 222
0508 220 222
vogroup.com.au<https://vogroup.com.au/>
                                [https://vogroup.com.au/assets/facebookNew.png] <https://www.facebook.com/vogroup>  [https://vogroup.com.au/assets/twitterNew.png] <https://twitter.com/vo_group>  [https://vogroup.com.au/assets/linkedinNew.png] <https://www.linkedin.com/company/vogroup>  [https://vogroup.com.au/assets/instagramNew.png] <vo://instagram.com/vogroup>

GOLD COAST
Suite 2405, Level 4
Southport Central Tower 2
5 Lawson St
SOUTHPORT QLD 4215              MELBOURNE
Level 17,
31 Queen St
Challenger Building
MELBOURNE VIC 3000              AUCKLAND
Level 4,
17 Albert St
Business Centre
AUCKLAND 1010




On 4 Oct 2018, at 12:41 am, Henock Desta <notifications@github.com<mailto:notifications@github.com>> wrote:


I think i figured out the issue: If you were logged in during the Facebook breach and was forcefully kicked out the app will display like @thunder87<https://github.com/thunder87> screenshot. If you log out by clicking File -> Logout in the toolbar on the top left it will work again.

**Comment by thunder87** [comment]
I can confirm that the method described by @digitalhank works!
