### ISSUE TITLE
Login don't is done

### ISSUE THREAD

**Issue by adrianoresende** [danielbuechele/goofy#42]
I entered www.messenger.com/t/ and is okay but in app i used "command + R" more times and unsuccessful.

![image](https://cloud.githubusercontent.com/assets/798755/7094542/a7f3579a-df98-11e4-8777-19bfdacf27ee.png)

**Comment by adrianoresende** [comment]
Success after close and reopen four times, when i open app, open messenger in browser with url:

https://messenger.com/login/fb_iframe_target/?userid= ... (some code)

And page is blank.

**Comment by moynard** [comment]
same problem here

**Comment by danielbuechele** [comment]
Running on the latest version (2.0.3)?

On 15.04.2015, at 21:23, Moises Medina <notifications@github.com> wrote:

same problem here

—
Reply to this email directly or view it on GitHub
<https://github.com/danielbuechele/goofy/issues/42#issuecomment-93538344>.

**Comment by xypaul** [comment]
Yeah 2.0.3 fixed the problem for me :+1:
