### ISSUE TITLE
Lastest update breaks the UI

### ISSUE THREAD

**Issue by ithieund** [danielbuechele/goofy#431]
It was OK in previous version, but this morning it asked me to install the new version then the UI is broken.

<img width="399" alt="screenshot at nov 22 08-56-17" src="https://user-images.githubusercontent.com/4217195/48877171-9e849800-ee34-11e8-9423-5a31c3091e5c.png">

**Comment by jklp** [comment]
Actually even easier, can you hit CMD-R to refresh the page and let me know if it's still broken?

**Comment by ithieund** [comment]
It's ok after the screen sleep. That's so strange

**Comment by jklp** [comment]
No worries.  I'll close the issue for now but feel free to reopen if you run into it again 🙂
