### ISSUE TITLE
Dark Mode because Usher Syndrome

### ISSUE THREAD

**Issue by mac4kent** [danielbuechele/goofy#433]

**Comment by jklp** [comment]
Hi, thanks for raising this - I'd really like to do this too though it's quite a bit of work, and I've been focusing on fixing the high priority bugs first before I start working on new features.  

In saying that there are already 2 bugs raised for this at #397 and #316 - so I'll close and mark as duplicate to make scheduling this easier.

Thanks!

**Comment by mac4kent** [comment]
Gooooooooooooooooooooooooood. Also I am full deaf and need have notification while app is close.
