### ISSUE TITLE
[Bug] Lost thread focus in compact mode

### ISSUE THREAD

**Issue by ithieund** [danielbuechele/goofy#434]
This is an annoying bug.
When I resize the windows into compact mode and chat with someone, that thread will be on the top.
But if we click outside (for example: click on desktop, or click on other windows) then click inside again, the focus will be on the 9th thread.

<img width="240" alt="screenshot at dec 24 22-17-15" src="https://user-images.githubusercontent.com/4217195/50402494-b485cf80-07c9-11e9-90c3-f9ee54d6bd8d.png">

Can you please fix it soon?

**Comment by jklp** [comment]
Might have been a bug in messenger.com as can't seem to replicate.

If it's still occurring please reopen and I'll check it out
