### ISSUE TITLE
Text replacement

### ISSUE THREAD

**Issue by lamortheureuse** [danielbuechele/goofy#437]
Please allow text substitution like it is mostly everywhere on Mac. In my opinion, I's an essential function of a chat application. 
Thank you:)

**Comment by jklp** [comment]
Ugh I would love this too though unfortunately isn't supported in Electron (is also is missing in Slack, whatsapp, etc).

Will leave ticket open as I personally do want to fix this myself.  

As a workaround, I currently use aText for substitutions but I know they're other apps (TextExpander etc) which also do the job

**Comment by jklp** [comment]
Oh it's duplicate of #333 so closing this issue.  Looks like there's a solution for #333 too so will hopefully be in v3.4.1
