### ISSUE TITLE
App shows blank screen after update to 3.4.0

### ISSUE THREAD

**Issue by olipachi** [danielbuechele/goofy#439]
3.3.5 now forces me to install and restart with 3.4.0, but the app appears to be broken. Won't load the UI, just stays on a white screen. I tried downgrading back to 3.3.5 but I get hit with a dialogue box to install 3.4.0, with no option to reject the update. 

<img width="800" alt="screen shot 2019-02-11 at 11 03 28 am" src="https://user-images.githubusercontent.com/9557059/52579884-c6a8e500-2dec-11e9-9350-99a4ef629663.png">

**Comment by jklp** [comment]
That's weird.  Can you delete Goofy and also delete your `/Users/user_name/Library/Application\ Support/goofy-core` folder - then re-install (you'll need to log back in again) and see if that works?

**Comment by olipachi** [comment]
Tried that, didn't work. 3.4.1 isn't working either.

**Comment by olipachi** [comment]
3.3.5 loads up correctly, but forces me to update to the broken version so it's unusable at this time.

**Comment by olipachi** [comment]
To clarify, I don't even get prompted for my FB credentials, and in 3.4.1, the FB Messenger gray icon that fades into the UI doesn't show up anymore. It did in 3.4.0.

**Comment by jklp** [comment]
That's really strange. v3.4.0 was when we moved over to Electron v4 (was previously on Electron v2) and v3.4.1 we no longer use a WebView but load messenger.com straight into the BrowserWindow - which should have fixed a couple rendering bugs.  

Can you try a couple things for me?  Can you load up https://messenger.com/login in Chrome in an incognito window and send me a screenshot of that? 

Also with Goofy v3.4.1 loaded, and you open the developer tools (cmd-option-i), click the Elements tab and send me a screenshot of that too?

Thanks!

**Comment by jklp** [comment]
Oh and one last question I don't suppose you can let me know  what country you're in?  I wonder if Facebook are A/B testing something in another country and we're seeing the effects of it here?

**Comment by olipachi** [comment]
Hmm. I tried launching messenger.com from my browser, and it looks like my corporate outbound proxy is blocking that traffic. I bet that's the issue. I wonder why it works on 3.3.5. 

<img width="799" alt="screen shot 2019-02-12 at 2 51 20 pm" src="https://user-images.githubusercontent.com/9557059/52667135-aef95b80-2ed5-11e9-850b-a888f494b978.png">

Attached the screenshot of the Elements tab, and it's empty, as it should be since my corporate network is blocking the traffic. 

I'll test from home just to make sure and get back to you. It's a shame though, since I almost exclusively use Goofy at work.

Also, I'm in the U.S.

**Comment by jklp** [comment]
Oh snap, yeah if it's the corporate proxy then that's probably why the screen is blank 😕 

The reason it worked in v3.3.5 was because we swapped from using https://facebook.com/messages to https://messenger.com in v3.4.0 - as using https://messenger.com allows users to login even if they don't have a Facebook account, and also has less styling problems.  

Unfortunately I can't think of a workaround off the top of my head - bar maybe using a VPN?

**Comment by olipachi** [comment]
So, confirmed the issue is my corporate proxy. Bummer.

Any way to disable the dialogue box forcing me to update from 3.3.5 to 3.4? I'd like to continue using 3.3.5, if possible.

**Comment by jklp** [comment]
Yeah for sure - I actually spent some time hacking together a preferences pane for Goofy v3.4.2 - where you can select between messenger.com or the old facebook.com/messages interface.  Give that a go and hopefully you can bypass your corporate firewall with that (please re-open this issue if you're still running into problems).
