### ISSUE TITLE
Notification badge flashing on 3.4.0

### ISSUE THREAD

**Issue by jasonrtsang** [danielbuechele/goofy#440]
After updating to 3.4.0, the dock notification badge (unread count) would flash instead of staying persistent like in 3.3.5. This is with "Desktop notifications enabled".

Attempted a reinstall including clearing the goofy-core system files, but issue remains.
Running macOS Mojave 10.14.3

Thanks!

**Comment by jklp** [comment]
Fixed in v3.4.1
