### ISSUE TITLE
Notification badge flashing on 3.4.2 bug

### ISSUE THREAD

**Issue by manwlios** [danielbuechele/goofy#446]
Hello there and thank you for this very usefull app.

The bug that supposed to be fixed in 3.4.1 is still present on 3.4.2.

macOS 10.13.6 with latest version of Goofy app.

Thanks!

**Comment by jklp** [comment]
Thanks, I noticed it was happening with named grouped messages (which has been fixed in 3.4.3).  

Was it happening in other places that you've noticed?

**Comment by manwlios** [comment]
iTo be honest i dont noticed it with named grouped messages. This happens also on single conversations.

**Comment by jklp** [comment]
Oh really?  Ok will have a poke around.  

By the way this might be related - but what language is your Facebook set as (is it English?).

**Comment by manwlios** [comment]
It is in Greek language, the default language of my facebook profile.

**Comment by jklp** [comment]
Ah damn, ok I know what it is ... will have to think of another solution for the unread badge.

If the flashing is annoying you can temporarily disable it in the macOS Notification Preferences - hopefully you can re-enable in the next version when it's all fixed!

**Comment by manwlios** [comment]
Thank a lot! You are great :)

**Comment by jklp** [comment]
Ok hopefully all fixed in 3.4.3 - please re-open if still flickering!

**Comment by manwlios** [comment]
Thank you so much! It seems to work fine now. Thanks again, take care.
