### ISSUE TITLE
Can't open 3.4.3 on 10.14.latest

### ISSUE THREAD

**Issue by KTamas** [danielbuechele/goofy#447]
It just doesn't launch. Well, it does but crashes immediately and complains to Electron missing/truncated file/something.

I even tried building it myself, same issue.

**Comment by jklp** [comment]
Hey @KTamas sorry I can't seem to replicate - do you mind posting a pic of the error message so I can debug? 

Also what version of 10.14 are you running (10.14.3?)


Thanks!

**Comment by KTamas** [comment]
I figured it out. I was using The Unarchiver 3.10 to unzip it, and it somehow doesn't unzip it correctly. The built-in OSX unzipper does, and so is the latest version of The Unarchiver, which now I upgraded to.

**Comment by jklp** [comment]
Ah nice one, thanks for the update 🙂
