### ISSUE TITLE
Failed to load resource: net::ERR_CONTENT_DECODING_FAILED

### ISSUE THREAD

**Issue by alvinnguyen** [danielbuechele/goofy#448]
Not sure if it's just me but I've started having this issue since yesterday.

The console is showing

Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
https://static.xx.fbcdn.net/rsrc.php/v3ikyG4/yU/l/en_US/9iWjDzDVJx0.js

And subsequently 
ErrorUtils caught an error: "<![EX[["%s did not fire because it has missing dependencies.\n%s","JS::call(\...". Subsequent errors won't be logged; see https://fburl.com/debugjs.
https://static.xx.fbcdn.net/rsrc.php/v3/yy/r/Xo4cbevAa2P.js

**Comment by alvinnguyen** [comment]
Issues seems to resolved itself.

**Comment by jklp** [comment]
Hey sorry for the delay only just got a chance to check github. Sweet ok lets leave close and can reopen if it happens again!
