### ISSUE TITLE
Can't Open Goofy

### ISSUE THREAD

**Issue by MilesConn** [danielbuechele/goofy#458]
So for some background. I was playing around with Goofy trying to get rid of the icon from the dock (so it doesn't distract me). I read about adding LSUIElement to the Info.plist to hide the icon. Well at first I didn't know it was supposed to be added to the .plist and I thought it had to be added  to the App's Defaults (I hope that's what it's called). So I ran `defaults write -app Goofy LSUIElement 1` and various versions of that. When that didn't work I finally realized that it had to be done in the .plist so I got rid of that. Well when I restart my machine Goofy wouldn't run. When I ran `open -a Goofy` I got 

> `LSOpenURLsWithRole() failed for the application /Applications/Goofy.app with error -10810.`

and the attached error report is here. I removed the preference from the .plist and the defaults and it still doesn't work. Curious if there is any workaround besides reinstalling. 
[Goofy_2019-07-03-162250_Maestros-Macbook.txt](https://github.com/danielbuechele/goofy/files/3359870/Goofy_2019-07-03-162250_Maestros-Macbook.txt)

**Comment by MilesConn** [comment]
I know I was playing around with the settings so I'm entirely responsible. More I'm just curious what exactly is breaking.

**Comment by jklp** [comment]
Hey sorry for the late reply - I just got back from holiday so just going through issues now.

I'm not entirely sure what's going on, though if you'd like to disable the dock icon there is a setting in the settings where you can hide / show the dock unread badge.
