### ISSUE TITLE
Spell Checking and Keyboard Shortcuts Not Working

### ISSUE THREAD

**Issue by bendywalker** [danielbuechele/goofy#46]
When typing a message in Goofy, neither OS X's spelling checking nor keyboard shortcuts work.

**Comment by peterjosling** [comment]
You need to enable spell check/substitutions for the input. Right click in the message field -> Spelling and Grammar -> Check Spelling While Typing. `spellcheck="true"` is already set on the element, so I'm not sure there's a way to force it.

**Comment by hashier** [comment]
Great! I was looking for exactly that. Maybe it's worth mentioning it in the README
