### ISSUE TITLE
Can't move window version 3.4.4

### ISSUE THREAD

**Issue by TerminalAddict** [danielbuechele/goofy#463]
Hi,
I just "auto updated" to version 3.4.4, and now cannot move the window.
I can resize on all sides, but cannot move by grabbing the title bar.

See video https://vimeo.com/353476890

**Comment by jklp** [comment]
Damn, ok so the update I released yesterday was for the new version of messenger and stupidly assumed Facebook would have migrated everyone to it by now (it was announced it June they'd have it done in the following months, and judging by your video looks like you're still on the older version)

Let me have a think how I can swap between the 2 different style sheets - else I'll revert the changes.

**Comment by jklp** [comment]
Cool I've just added back the old style for just dragging the window - could you let me know if that works?  

I'm hesitant to load the full pre-3.4.4 CSS, as the old layout for messenger.com will soon be going away, and don't want to spend time on something which will be gone in a couple weeks / months time.  

Hopefully that should be enough to get it usable again until the new version of messenger.com rolls out to everyone.

**Comment by TerminalAddict** [comment]
yup that fixed it . .thanks
