### ISSUE TITLE
Responsiveness issue on new messenger design

### ISSUE THREAD

**Issue by ImmersiveX** [danielbuechele/goofy#464]
Present on 3.4.6
Issue arises when @ media (max-width: 900px) comes into play.

Active contacts:
![image](https://user-images.githubusercontent.com/17133099/63216783-0b665d80-c13b-11e9-96c2-d1ddcfe8ed89.png)

Message requests:
![image](https://user-images.githubusercontent.com/17133099/63216798-32bd2a80-c13b-11e9-9840-40d9ef37d07c.png)

**Comment by jklp** [comment]
Just checked it out and am hesitant to fix as it looks like a bug on messenger.com (not the electron app).  

Just worried that once Facebook fix it - it might have flow on effects on the fix applied on the Goofy app.  I think we should wait this one out (unless I'm missing something)?

**Comment by ImmersiveX** [comment]
Hmmm, it does seem so, I never thought to check messenger.com
I'd leave it to Facebook to fix their mess.

**Comment by jklp** [comment]
No worries, thanks 🙂
