### ISSUE TITLE
white screen - ERR_CONTENT_DECODING_FAILED

### ISSUE THREAD

**Issue by gpabijan** [danielbuechele/goofy#465]
Hello Guys,
For some days I can't run app at all. I think it's since last OS update. I tried to remove cache, logout, reinstall app with full cache removal. Nothing works. After logout I can login one more time and stuck at the same point.

`3static.xx.fbcdn.net/rsrc.php/v3/yQ/r/SRUnOLoVCV0.js?_nc_x=UuTtC8_6uSG:1 Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
RfBV37Aoeh_.js?_nc_x=UuTtC8_6uSG:51 ErrorUtils caught an error: "JS::call("WebStorageMonster", "schedule", ...) did not fire because it has mi...". Subsequent errors won't be logged; see https://fburl.com/debugjs.`

OS: 10.14.6
App_version: 3.4.6
<img width="1093" alt="Zrzut ekranu 2019-08-19 o 11 13 01" src="https://user-images.githubusercontent.com/27371293/63253767-bded0c00-c272-11e9-9f82-7e9eec8d782d.png">

**Comment by gpabijan** [comment]
fix itself after few days :) thx

**Comment by jklp** [comment]
Sorry for the late response - was going to check this out on the weekend. Glad to see it came right!
