### ISSUE TITLE
Goofy main window doesn't show at all

### ISSUE THREAD

**Issue by gpeuc** [danielbuechele/goofy#466]
Hey,

about 2 days ago Goofy simply started not showing up at all. I've reinstalled it just for good measure, and it still doesn't show the main window.

The app is loaded, I can select it from the menu, the menu bar appears, I can go into preferences, check for updates, etc, but no matter what I do the app simply doesn't have any visible presence at all.

Latest Goofy, downloaded today from GitHub, OS is as follows:

![Screen Shot 2019-10-04 at 10 27 57](https://user-images.githubusercontent.com/44162846/66197113-a38bb800-e691-11e9-8369-e3aecd37810d.png)

**Comment by gpeuc** [comment]
If I can get it to load at least that window, you can just hit refresh (cmd+R) and it will usually manage to reload content inside that window. But approximately 50% of the time the window itself fails to instantiate. It simply doesn't load up at all. Even when I press Mission Control button to expose all windows just to see if it maybe loaded outside of the viewport, it's not there. It simply does not load up the main window at all.

**Comment by gpeuc** [comment]
On Catalina I stopped having this problem. Loads every time. 

<img width="541" alt="Screen Shot 2019-10-22 at 09 56 12" src="https://user-images.githubusercontent.com/44162846/67271352-3dd16580-f4b2-11e9-96fb-af7240b6bbc5.png">

**Comment by jasgggit** [comment]
Hi, same here, for a long time now.
Still on Mojave.
Regards.

**Comment by jklp** [comment]
@gpeuc @jasgggit @samlehman Hey guys sorry I've just started a new job so haven't had the headspace to look at Goofy. 

I'm only on Mojave here but my window seems to load fine. 

Can you start by deleting Goofy, then deleting the following folders 

-  /Users/User name/Library/Application Support/goofy-core
-  /Users/User name/Library/Application Support/goofy-builder (if it's there)
-  /Users/User name/Library/Application Support/goofyapp (if it's there)
- And any other folder starting with goofy

Then re-installing Goofy and see if it loads?

Another question - if you visit messenger.com on your browser does it load there?  If so, is it the new layout or are you still on the old layout?  

Thanks!

**Comment by gpeuc** [comment]
Pffff, job, what, you need to pay your bills and eat food? Who does that! 😄 Congrats in the job man.

After I delete everything and reinstall Goofy, it works fine.

At the moment the UI between Messenger and Goofy is synchronised.

**Comment by jasgggit** [comment]
Hi, thanks for a good job.
All working here now.
Regards.
JG
