### ISSUE TITLE
After updating mac to Catalina red badge notification doesn't appear on the Dock

### ISSUE THREAD

**Issue by stopsopa** [danielbuechele/goofy#467]
I hear the sound when somebody is writing but can't see red badge on the Dock on the app icon.

Additionally app is not visible on the list in Settings -> Notification, so I can't just turn notifications on.

I assume that app is incompatible with Catalina changes to the notifications system and needs to be reviewed/updated.

I'm creating this as a new Issue because other issues mentioning problem with badge notifications seems to be old.

**Comment by jklp** [comment]
Fixed in 3.4.7 - just needed to rebuild to ask for push notification permissions.
