### ISSUE TITLE
Archive => Automatically Move to Next Conversation Functionality

### ISSUE THREAD

**Issue by jonleung** [danielbuechele/goofy#469]
## Current Functionality

1. Archive a message
2. Now the user is in a state that is empty / nothing is selected. The next conversation is not shown and when I do `Select Next Conversation` presumably because I'm not in a current conversation.

So in order to go to the next message, I'll need to move my hands to click on the next message instead of being able to use the awesome keyboard shortcuts you baked into the app.

## Proposed Feature

So the original functionality above does the same thing. Create a new shortcut key, Cmd + Opt + A which is "Archive and Advance to Next Conversation"

I'm no UX designer so let me know if you think of a better idea!

**Comment by jklp** [comment]
Hey @jonleung thanks for the suggestion! 

Unfortunately the spirit of Goofy is to not make too many changes to the standard messenger.com website, but instead - slightly enhance it with shortcuts etc.  

I think to fix this would require a bit too much "inside knowledge" of how messenger.com works behind the scenes, and feel like fixing this might break other things when messenger.com do fix this bug.

Sorry!
