### ISSUE TITLE
How to turn off dark mode

### ISSUE THREAD

**Issue by t2wu** [danielbuechele/goofy#473]
My system is not in dark mode. But I did a fresh install of Goofy and it comes with dark mode by default. How do I turn it back into light mode?

**Comment by jklp** [comment]
Oh that's embarrassing ... literally just pushed that build out and didn't check the settings on first load.  To work around, go into preferences and enable, then disable dark mode.

Sit tight I'll do a hot fix now and release 3.5.4 😅
