### ISSUE TITLE
JavaScript error in the main process

### ISSUE THREAD

**Issue by lensherm** [danielbuechele/goofy#474]
As the application is started, the following error message comes up:

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Code signature at URL file:///Users/len/Library/Caches/cc.buechele.Goofy.ShipIt/update.1SlPaJT/Goofy.app/ did not pass validation: code failed to satisfy specified code requirement(s)

**Comment by daninko** [comment]
I had the same problem, realized that it was due to being an old version (3.4.something). If you download the latest from the releases page, the error should go away.

**Comment by jklp** [comment]
Ah right makes sense - @lensherm Can you confirm what version you're working on - and also where did you see the error (was it a popup), can you send a screen shot?

Thanks!

**Comment by lensherm** [comment]
It was the latest version as of the submission. It was a popup, but I
finally ended up removing the application and reinstalled it from scratch.
So far no issues.

**Comment by jklp** [comment]
Ah ok, will close for now but feel free to reopen if you run into it again 🙂

**Comment by itsdarrylnorris** [comment]
I have been running to the same issues for a couple months now. Updating to the latest version fixes the issue. It will be nice if we have an auto-updater feature build in the app.
