### ISSUE TITLE
Always collapse the sidebar?

### ISSUE THREAD

**Issue by brownsugar** [danielbuechele/goofy#475]
Hi, currently the left sidebar only collapse when the window width is smaller than 901px, is there any option to make it always collapse even in fullscreen mode? Thanks.
![image](https://user-images.githubusercontent.com/2935980/73132298-2fb45780-4054-11ea-82b6-740458cafc98.png)

**Comment by jklp** [comment]
@brownsugar Hi!  Unfortunately the goal of Goofy is to have as light a touch as possible with the default messenger.com CSS. 

In saying that - if you'd like to submit a PR and maintain the option going forward (when the CSS changes etc) I'd be more than happy to merge it in 🙂

**Comment by jklp** [comment]
@brownsugar Sorry for the delay - just merged your PR and will be in the next build!
