### ISSUE TITLE
Can't move the window

### ISSUE THREAD

**Issue by petr-ujezdsky** [danielbuechele/goofy#491]
The window is missing draggable area on top. If I try to move the window from top part, it only selects text.
Even the part around the 3 main buttons (close, minimize, fullscreen) does not act as draggable, only selects text again.

App version `3.5.4 (3.5.4.154)`
MacOS `Catalina 10.15.7 (19H114)`

**Comment by petr-ujezdsky** [comment]
Not reproducible after upgrading MacOS to `BigSur 11.1 (20C69)`. Closing.

**Comment by Calorion** [comment]
Are we removing compatibility with all operating systems prior to Big Sur?
