### ISSUE TITLE
Doesn't support Mac OS 10.9

### ISSUE THREAD

**Issue by mcescalante** [danielbuechele/goofy#51]
I am running 10.9.5 and I can't open Goofy, says that it requires 10.10 or newer. Are there plans for adding support for Mavericks? :smile:

**Comment by danielbuechele** [comment]
No. Sorry.

**Comment by blha303** [comment]
Sorry to necro an old thread, but it's relevant.
Can you add something indicating this to the main page? I see that it's in the FAQ, but most people (based on my own experience) would download the app without clicking to the FAQ first and then be disappointed.
