### ISSUE TITLE
Error when updating to 2.0.3 - download hosting broken. Switch to Github Releases please!

### ISSUE THREAD

**Issue by ialexryan** [danielbuechele/goofy#60]
I get this error when trying to update from 2.0.2 to 2.0.3. At first I assumed that there was a code signing issue, but when I checked my network activity I realized that nothing had been downloaded.

I then checked https://dani.taurus.uberspace.de/goofyapp/update.xml for the info about the latest version.

I then checked the link provided for 2.0.3 (https://dani.taurus.uberspace.de/goofyapp/download.php) and, sure enough, it's broken or down.

Please please please switch to using Github Releases for download hosting! It's free and super fast and will never have issues like this. I really can't recommend it strongly enough.

![screen shot 2015-04-15 at 12 30 03 pm](https://cloud.githubusercontent.com/assets/2292782/7167586/2c93c52c-e36b-11e4-9285-dd165813f5ec.png)

**Comment by ialexryan** [comment]
cc/ @JadenGeller can attest to how wonderful Github Releases is.

**Comment by danielbuechele** [comment]
Working now?

On 15.04.2015, at 21:37, Alex Ryan <notifications@github.com> wrote:

cc/ @JadenGeller <https://github.com/JadenGeller> can attest to how
wonderful Github Releases is.

—
Reply to this email directly or view it on GitHub
<https://github.com/danielbuechele/goofy/issues/60#issuecomment-93542362>.

**Comment by ialexryan** [comment]
Yes, thankfully. But pleeease still switch to Github Releases...I really can't fathom why you'd prefer something unreliable that you have to pay for, to a free global CDN with 99.999% availability...
