### ISSUE TITLE
Small header appears in collapsed sidebar

### ISSUE THREAD

**Issue by podgib** [danielbuechele/goofy#63]
When the left sidebar is collapsed to its mini form, a box with the word 'messages' is half-visible at the top of the sidebar.

![screen shot 2015-04-16 at 12 39 56](https://cloud.githubusercontent.com/assets/2173772/7180068/d8c2b28e-e435-11e4-804f-1dad284349f5.png)

**Comment by JadenGeller** [comment]
+1
