### ISSUE TITLE
Paste image

### ISSUE THREAD

**Issue by johnhadrill** [danielbuechele/goofy#64]
Would be useful to be able to paste image by using cmd+V. This can be achieved in webkit relatively easily, and would be great for sharing screenshots!

http://jsfiddle.net/KJW4E/519/

**Comment by peterjosling** [comment]
This has already been implemented in #55, just waiting for the code to be cleaned up and merged in.

Safari doesn't actually support e.clipboardData.items (ugh), so the code you posted isn't enough. The implementation I came up with catches the paste event in Swift and sends the image data directly to a Javascript function.
