### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by samvasko** [danielbuechele/goofy#65]
I am getting a fatal crash when I start Goofy.
http://hastebin.com/xikoletero.txt

**Comment by JadenGeller** [comment]
Thanks for the bug report! It seems that we're unintentionally unwrapping an optional value in the applicationDidFinishLaunching method. I'll try to fix this (and let you know!) once I get a chance.

**Comment by tuzebra** [comment]
I have this problem too.
