### ISSUE TITLE
Use chrome(ium) webview instead of Safari

### ISSUE THREAD

**Issue by RvMouche** [danielbuechele/goofy#70]
Thinking about #69 I thought it may be cool to use a Chrome webview instead of Safari because support phone calls and more 'edgy' features is possible than too. Would probably take some time to make though and is not a priority. Also cool so one day there could be a whatsapp version of Goofy (Mickey?).

Found this while googling: 
- https://bitbucket.org/chromiumembedded/cef
- http://www.magpcss.net/cef_downloads/

**Comment by anilanar** [comment]
I'm not sure if I would want this to happen, as Chrome/Chromium and apps based on them are battery hogs in OSX. That's why I had to stop using Atom editor and go back to good old Vim :(

**Comment by danielbuechele** [comment]
this would basically be a complete rewrite of the app. won't happen. sorry.
