### ISSUE TITLE
Spell check enhancement

### ISSUE THREAD

**Issue by kaiforsyth** [danielbuechele/goofy#72]
Is it possible to get an inline spell check feature added? Would be really useful.

**Comment by xxdavid** [comment]
You can enable it manually.
`Edit` -> `Spelling and Grammer` -> `Check Spelling While Typing`

**Comment by Leland** [comment]
Good tip by @xxdavid; this should definitely be enabled automatically however!

**Comment by TCB13** [comment]
+1 on this. Thanks for the tip!

**Comment by ip2k** [comment]
There is no `Edit -> Spelling and Grammer` for me on `10.12.6 (16G29)` using `Version 3.2.2 (2001)`
