### ISSUE TITLE
ctrl+tab switches to the next conversation.

### ISSUE THREAD

**Issue by darenju** [danielbuechele/goofy#75]
It would be nice to mimic the behavior of the Messages.app. For example, ctrl+tab goes to the next conversation, and ctrl+shift+tab goes to the previous conversation. I can try to work on that, but since you know it better than me, you'll probably come off with a better workaround than me.

**Comment by danielbuechele** [comment]
This should already be implemented: CMD + [ for example

**Comment by darenju** [comment]
Then this isn't really AZERTY keyboard friendly. No direct [ on these. But I just saw issue #62, and I think the idea is here. Just a few tweaks and it should work. I guess...

**Comment by danielbuechele** [comment]
You can use System Preferences to map these to whatever you like.
