### ISSUE TITLE
Remove "Open in chat" option in "Actions" menu

### ISSUE THREAD

**Issue by kalprestito** [danielbuechele/goofy#8]
The actions menu shows the "Open in Chat" option, which does nothing in Goofy.

**Comment by danielbuechele** [comment]
Do you have a good solution for this? Just hiding it by counting (e.g. `nth-child`) is not a good solution. However, the menu item does not have an ID or a unique class.

**Comment by kalprestito** [comment]
I implemented a script that searched for commands in that menu whose text
is `Open in Chat`. However, there are two problems:

1. It does not work in other languages
2. That menu seems to be loaded into the DOM when you first click the
`Actions` button, so my script simulated a click. Nonetheless, the page
loaded the menu again and the option returned.

**Comment by danielbuechele** [comment]
I actually think it's okay to leave this menu item in there, even it does not do anything. But as long as we don't have a good way of hiding it, I'd rather leave it in than such a hacky solution. What do you think?

**Comment by kalprestito** [comment]
Yeah, I don't think that should be done, given how error-prone it would be.
