### ISSUE TITLE
Backspace sometimes doesn't work

### ISSUE THREAD

**Issue by AlesJiranek** [danielbuechele/goofy#81]
Sometimes when I type some message and make mistake a try to use backspace to delete it it doesn't work. But when I send message it is correct.
So in background deleting works but message in text box doesn't change and whole message stays in it.

**Comment by bumbu** [comment]
Also have this thing from time to time. It appears only after some time. Restarting the application helps.

**Comment by neongreenfruit** [comment]
I realized this this morning. thought I'd put my two cents in!

**Comment by Ezerbeth** [comment]
A year later... still happening. Time to move to a competitor that addresses bugs...
