### ISSUE TITLE
Crash for some links when getting a security warning

### ISSUE THREAD

**Issue by richardtagger** [danielbuechele/goofy#82]
If you try to share a link that Facebook have flagged it pops up a security warning which causes an instant crash in Goofy.

example link: https://vid.me/WaJr

**Comment by danielbuechele** [comment]
Can someone provide me with some more links that trigger these security warnings? The one above doesn't trigger it anymore for me, although it did when I tried first.
(Also, feels a bit weird to ask for suspicious links on github ;-))
