### ISSUE TITLE
⌘+W to close conversation, not whole window on OSX

### ISSUE THREAD

**Issue by Sheraff** [danielbuechele/goofy#86]
To be contingent with OSX's standard behavior, ⌘+W should close the active conversation (like clicking on the little grey ╳.

The thing is, this ╳ only appears when you start a new conversation (clicking on the blue notepad or pressing ⌘+N). So to be contingent with messenger's own behavior, this is the only conversation that ⌘+W should be able to close...

So I'm not sure what's the appropriate thing to implement here. It feels like there's a conflict of paradigms.

**Comment by peterjosling** [comment]
cmd+w behaviour matches what the native Messages app does — closing a conversation in that is cmd+shift+w.

**Comment by danielbuechele** [comment]
Is there a way to "close" a conversation? Or is it the same as deleting it?

**Comment by Sheraff** [comment]
I think you can only close a new conversation (this doesn't delete it). You get 'new message to ...' and the ╳. 
![screen shot 2015-05-12 at 18 06 05](https://cloud.githubusercontent.com/assets/1325721/7592053/97908e7a-f8d1-11e4-88cb-65f227bcb2be.png)

**Comment by danielbuechele** [comment]
But this only applies to new conversations. I prefer having CMD+W close the window. But we could think about using CMD+Shift+W to close a new conversation. Although this is probably a rarely used feature.

**Comment by Sheraff** [comment]
Totally. I'm not even saying I'd use it. It's just for coherence with the OS.

**Comment by Leland** [comment]
There's precedent in both directions in OS X apps – ⌘+W in Messages closes the entire chat window; ⌘+W in Safari closes the active tab.

I think I like the latter action better: there are no other possible windows available for the Goofy app, and so I can't think of a possible reason why a user would want to close the conversation window. +1 for making ⌘+W close the current conversation and ⌘+Shift+W close the entire window.
