### ISSUE TITLE
How are our user credentials handled? Where are they stored in the app?

### ISSUE THREAD

**Issue by hgonzalez94** [danielbuechele/goofy#87]
Like the title asks, I'm just wondering where my credentials get saved to when I'm using the app, or if they're just passed for a token to FB's api? How secure is my information with this app?

**Comment by RvMouche** [comment]
None of it, it's just a 'webview' so it's the same as messenger.com. Gets
trough Safari

**Comment by danielbuechele** [comment]
What @RvMouche said. Goofy has a shared cookie store with Safari. So when you login the credentials are sent directly to messenger.com a token is stored in your Safari's cookie store.
