### ISSUE TITLE
Titlebar between fullscreen and new not draggable

### ISSUE THREAD

**Issue by RandyWalker** [danielbuechele/goofy#88]
I can't drag the window around from the space between the fullscreen button and the "new" button.

![goofy](https://cloud.githubusercontent.com/assets/885610/7674268/6661c64c-fcf1-11e4-98a8-6ef7d955502e.png)

**Comment by bendywalker** [comment]
I just assumed this a limitation for one reason or another. If you can make it possible to drag a window using this area, that would be awesome!

**Comment by danielbuechele** [comment]
fixed in latest release. Thanks four your feedback!

**Comment by RandyWalker** [comment]
Awesome, thanks! 👍🏻
