### ISSUE TITLE
"Flash player upgrade required", so no video playback

### ISSUE THREAD

**Issue by GandalfSaxe** [danielbuechele/goofy#89]
Flash is installed and works fine on messenger.com in Safari. Any suggestions?

**Comment by danielbuechele** [comment]
So, it's not possible to load plugins like Flash inside WKWebView. However, I don't know why Facebook assumes that Goofy isn't able to play HTML5-video. Perhaps we need to set some kind of user-agent. Any ideas?

**Comment by RvMouche** [comment]
Facebook also on Safari want Flash (I don't have it and can't play video's
in Safari), maybe the mobile safari user agent would work?

**Comment by danielbuechele** [comment]
I have flash installed on my Safari, but still it uses HTML5 video.
They are setting a couple of classes on the body element, that might be related: `<body class="webkit safari mac x2 Locale_en_US" dir="ltr">`

**Comment by ntpeters** [comment]
Could a short-term fix be to at least open the video link in the default browser when clicking it?  As it stands there is no way to view videos in Goofy, but offering the option to open the video as a link would at least be a better temporary solution than not being able to view it at all.
