### ISSUE TITLE
Send file image doesn't work

### ISSUE THREAD

**Issue by jopereyral** [danielbuechele/goofy#90]
Every time i wan't to send some images, it looks broken.

Thanks.

**Comment by danielbuechele** [comment]
Can you be a little more specific on this? A screenshot would also help.

**Comment by jopereyral** [comment]
Yes, when using this functionality
![screen shot 2015-05-19 at 9 47 34 pm](https://cloud.githubusercontent.com/assets/5117647/7718055/c81828ec-fe70-11e4-98c1-fd41c32b27e3.png)

**Comment by danielbuechele** [comment]
I didn't mean a screenshot of the button which looks perfectly fine, but a screenshot of what looks broken. Sorry, I don't get it.

**Comment by RvMouche** [comment]
I just got the same issue so let me describe:
When I click on the upload image button and go to a picture, click on the space bar Goofy crashes. Besides that after I restarted I can select any file and it just doesn't upload, really weird.

Another question, can we add the old upload feature back next to this? Was a lot easier in quite some situations :) (and can we add support for PDF's)

**Comment by danielbuechele** [comment]
Oh, now I understand. The image doesn't "look broken" as @jopereyral said, but the upload isn't working at all. Yes, I'll look into that.

**Comment by NateFuller** [comment]
Replicated this myself on Mac OS X 10.10.3.

Selecting a photo in the finder window then pressing space bar (in order to preview the image) crashes the app. A snippet of the error log if that helps..?


Double clicking or selecting and then pressing "Open" closes the upload window with no visual feedback indicating error, other than the photo not uploading at all.

**Comment by tsujamin** [comment]
Still happens in 2.1.3. When you hit the picture icon a file browser opens with which you can select an image, however upon selecting the image nothing happens. You must log on to messenger.com to actually send an image

**Comment by chibicode** [comment]
Confirming that uploading is failing as of today on 2.1.3...

**Comment by cleiton-tavares** [comment]
+1

**Comment by jklp** [comment]
Fixed, created pull request here https://github.com/danielbuechele/goofy/pull/131
