### ISSUE TITLE
Emoji instead od Facebook emoticons

### ISSUE THREAD

**Issue by silvenon** [danielbuechele/goofy#93]
They're much nicer and that's what iOS Messenger has.

**Comment by RvMouche** [comment]
+ 1, I found some code for this in the goofy project a while ago and thought it was the case in v1. So hopefully it can return :)

**Comment by larswinter** [comment]
You could use cmd + ctrl + space to bring up the system wide emojis just like using the emoji-keyboard on iOS.

**Comment by silvenon** [comment]
Yeah, but it's faster if they are automatically added, replacing text smileys.

**Comment by joes33** [comment]
I think for me is best only standard emoticons, sample: http://www.thefbemoticons.com

**Comment by danielbuechele** [comment]
fixed
