### ISSUE TITLE
Copy–pasting an image into the input field does not work

### ISSUE THREAD

**Issue by teddybradford** [danielbuechele/goofy#95]
On www.messenger.com you can copy–paste images directly into the input box, but in Goofy that functionality doesn't seem to work.

**Comment by ivancuric** [comment]
It seems to be an issue with Safari and the Safari webview which Goofy uses.

**Comment by cortices** [comment]
Yes. Chrome supports this natively, Safari doesn't. Perhaps there's some workaround possible, by storing the clipboard image to /tmp/ and then triggering a JS image upload?
