### ISSUE TITLE
Goofy hates my Russian (Translit) IME (now with proof)

### ISSUE THREAD

**Issue by KTamas** [danielbuechele/goofy#97]
I use https://github.com/archagon/cyrillic-transliterator for writing Russian (well, Ukrainian at the moment but nevermind that) under OSX. It acts as an IME, and had no issues with it, until I tried writing something in Goofy. The first word is okay, but then the it removes the space after that and everything goes haywire. 

It also seems somewhat random, as I could not reproduce it just now but it is definitely happening. I will try to make a screen recording when it happens again.

**Comment by KTamas** [comment]
There, I got it!

Here is a video of the bug: 
https://www.youtube.com/watch?v=H3hKH0wlQC8&feature=youtu.be

**Comment by yaycmyk** [comment]
@KTamas Does it work correctly in messenger.com? I doubt the author is messing with the input fields when repackaging the app.
