### ISSUE TITLE
EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

### ISSUE THREAD

**Issue by lubieapki** [danielbuechele/goofy#98]
I am getting EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
How to fix it?
![zrzut ekranu 2015-06-09 o 09 57 46](https://cloud.githubusercontent.com/assets/6787484/8053131/041f842a-0e8e-11e5-89a7-100102e9f1df.png)

**Comment by danielbuechele** [comment]
That's because the JavaScript file is not found. You need to run the `gulp` task.
