### ISSUE TITLE
Input field caret not showing, input field not updating until focus is lost

### ISSUE THREAD

**Issue by Nailer** [danielbuechele/goofy#99]
Running OSX 10.10.3 and Safari 8.0.6

The input field caret does not blink, nor does the text field get updated past the initial keystroke.

Example: 
I try to write "We are friends"
The input field will show "W" until I click somewhere outside the input field, which will cause the text field to update.

The input field will, however, update continuously when deleting text using backspace

**Comment by danielbuechele** [comment]
This is a bug of messenger.com. Try it out in Safari. Already talked to FB and sent them a bug report.

**Comment by foxyq** [comment]
Fuuny it's working in Chrome, but not in Safari. I suppose the app is written somehow using Safari, right?

**Comment by Serneum** [comment]
Interestingly enough, I see this on one of my Macs but not the other. Both are using the latest version of the app. I had a feeling it was an issue with messenger.com, but then I don't know why only one of my computers would see the issue

**Comment by hashier** [comment]
Fixed for me (Just as information)

**Comment by foxyq** [comment]
^ awesome :) thanks for info
